### ISSUE TITLE
The Future of Camera Roll?

### ISSUE THREAD

**Issue by TGNYC** [kollerlukas/Camera-Roll-Android-App#1]
Hey Lukas,

Do you plan to keep Camera Roll open-source? How is the development process going (read: update times, plan for support, new features)?

I think your app has really great potential, and it definitely is one of the best looking Material Design gallery apps on Android. I'll be featuring it on my [Android App Guide](http://quickbrownfox.xyz/android/) soon.

Keep up the great work!

**Comment by TGNYC** [comment]
Also, if you plan on keeping it open-source (which I hope you do), I recommend you also release the signed APK files on Github and on F-Droid.

**Comment by kollerlukas** [comment]
I will always keep Camera Roll open source!
I will release the apk on Github & F-Droid as soon as possible.

As for new features, I have planned to add a simple photo editing tool and I am always open for suggestions.

I will try to keep update intervalls as small as possible. But as for now Android Development for me is still a hobby.

Thanks for the feedback!

**Comment by TGNYC** [comment]
The ability to delete make and delete folders in the main Camera Roll would be nice.

**Comment by TGNYC** [comment]
And the Show Hidden Folders option in the ellipsis menu should also show the excluded folders, so that you can unexclude them (which I can't figure out how to do at all).

**Comment by TGNYC** [comment]
Also, do you mind me using the [Camera Roll banner](https://github.com/kollerlukas/Camera-Roll-Android-App/blob/master/camera_roll_banner.png) in your README.md on my app guide? I'd appreciate it.

**Comment by kollerlukas** [comment]
Of course! You can use the banner.

**Comment by TGNYC** [comment]
Just a note:

I think you should use the icon in the banner as the icon of the app, and I think that you should also release the .apks on Github as well.
