### ISSUE TITLE
Floating action button

### ISSUE THREAD

**Issue by lopolon** [kollerlukas/Camera-Roll-Android-App#100]
Can you add a FAB to delete pictures in nested recyclerview where all the albums are displayed ?
Personally i always delete pictures without opening the albums because i'm comfortable to delete
more pictures of different albums in a single page
![screenshot_20171001-181028](https://user-images.githubusercontent.com/32436364/31057250-f8424cea-a6df-11e7-8bd0-746cb18d6c25.png)

**Comment by kollerlukas** [comment]
duplicate to issue #74
