### ISSUE TITLE
Loop video and fullscreen playback

### ISSUE THREAD

**Issue by Wiredframe** [kollerlukas/Camera-Roll-Android-App#101]
Awesome gallery! Thing I miss in every gallery and I hope you will add: 

- Loop videos
- Play videos in fullscreen (fit to screen) automatically

Hope you'll add these things 👍

**Comment by kollerlukas** [comment]
Videos should loop already. And I am sorry but I don't know what you mean by "Play videos in fullscreen".

**Comment by Wiredframe** [comment]
For "Play videos in fullscreen" please see here: https://github.com/kollerlukas/Camera-Roll-Android-App/issues/120
