### ISSUE TITLE
Pics lower than 68x68px don't load

### ISSUE THREAD

**Issue by uchchishta** [kollerlukas/Camera-Roll-Android-App#104]
Version: 1.0.2

Any pics lower than 68x68px is not shown in the main app, but I can open them by selecting to `Open with` Camera Roll via file browser.

**Comment by uchchishta** [comment]
Er.. It took a MediaScan to load it. But I don't know why that was required, because I had cropped a pic to 68x68px and it showed up. Further cropping it to lower resolutions, those pics did not..

**Comment by kollerlukas** [comment]
@uchchishta With what app did you crop the pic?
Did you save the cropped picture in the same location or as a copy in a new location?

**Comment by uchchishta** [comment]
I cropped till 68px in Camera roll and then lower than that from another gallery (that very old neutred version of Quickpic ;) ). It automatically saved it as different `image~01.jpg` in the same folder

**Comment by uchchishta** [comment]
@kollerlukas I can't reproduce it now. I think this somehow got solved.. I'll close this?
This is one of the most beautiful apps I've seen ^^ thanks!!
