### ISSUE TITLE
Option to disable sliding animation

### ISSUE THREAD

**Issue by Jiack214** [kollerlukas/Camera-Roll-Android-App#108]
Sometimes sliding images is a bit laggy on my device.
I think the problem is the cool animation... It doesn't occur in any other gallery app.
So I would like to have an option to disable it.

**Comment by kollerlukas** [comment]
What device and Android version are running?

**Comment by Jiack214** [comment]
Android 7.1.2 (LineageOS 14.1) on LG G3

**Comment by fredgolightly** [comment]
Yeah would be nice without the animations altogether :) 5x it's fast but tbh animations are distracting

**Comment by fredgolightly** [comment]
On a Pixel 2 now but the interface animations drive me nuts...any chance this could be disabled?
Pixel 2, Android 8.1

**Comment by kollerlukas** [comment]
@fredgolightly Do you really don't like the animations? 😞
