### ISSUE TITLE
"Show hidden folders" doesn't work

### ISSUE THREAD

**Issue by Yixuan-Wang** [kollerlukas/Camera-Roll-Android-App#117]
The "Show hidden folders" option in menu doesn't work. It also won't work when MediaRetriever is enabled. 
I'm using OnePlus 5(cheeseburger) with Resurrection Remix ROM 5.8.5(Android 7.1.2), Camera Roll version 1.0.3

**Comment by kollerlukas** [comment]
Is this issue stull present?

**Comment by Yixuan-Wang** [comment]
Oops, I suddenly realize that this option won't show excluded folders, right?
