### ISSUE TITLE
SD card access

### ISSUE THREAD

**Issue by LoBelly26** [kollerlukas/Camera-Roll-Android-App#123]
Hi, very good job, but I can't delete images from the sd card. When the application tells me to go and click on the root folder, i do it but then it doesn't work. Sorry for my english, i'm italian. I hope you'll understand my problem (Huawei Mate S)

**Comment by kollerlukas** [comment]
Does the app give you an error? Or does it just say "Done", and the files are still there?

**Comment by LoBelly26** [comment]
It says "done" but then the app tells me, an another time, to go and click on the root folder in loop

**Comment by RoestVrijStaal** [comment]
I've faced this issue as well. 

When I've clicked to view a pic on external SD in main screen and try to delete it. The dialog for selecting the root of the external SD to give Camera Roll write permissions goes away in an eyeblink. 

I've found a workaround by selecting the image in the main view first, then delete it. In that case the "permission dialog" does not go away immediately. So by that way you could set the right permissions for Camera Roll.

**Comment by LoBelly26** [comment]
I thought about it, but i can't give write permission to the app from settings, the bar where i can enable the permission is unclickable

**Comment by kollerlukas** [comment]
same as #63
