### ISSUE TITLE
Opening photo from other source doesn't allow to take action

### ISSUE THREAD

**Issue by alekksander** [kollerlukas/Camera-Roll-Android-App#128]
example:
Take photo with OpenCamera, select to preview it, select to open with Camera Roll — photo turns out terrible: — can't delete from Camera Roll. Photo is okay, but want to compare with previous from session by sliding it left — can't do that with Camera Rolll either. Is it intended? This stops me from using this great app as my main and default.

**Comment by kollerlukas** [comment]
same as #110
