### ISSUE TITLE
Req: use same size thumbnail in portrait & landscape

### ISSUE THREAD

**Issue by fredgolightly** [kollerlukas/Camera-Roll-Android-App#129]
I just realise the app generates two sets of thumbnails because switching between portrait and landscape mode for some reason resizes the thumbnails thus requiring new ones to be regenerated.

Any chance you could halve the app's cache by simply reusing the same ones for both?

**Comment by kollerlukas** [comment]
I already changed this back in January https://github.com/kollerlukas/Camera-Roll-Android-App/commit/c0f2802e0f8914f238a9cae5844c7bbbdffac57b#diff-88a602ca92c85b408e86eb30c3e48a19
But I haven't published an update yet.

`.diskCacheStrategy(DiskCacheStrategy.RESOURCE)`
only caches the Source so only one instance is stored in the cache.
