### ISSUE TITLE
Remove certain options from picture view overflow menu

### ISSUE THREAD

**Issue by jahirfiquitiva** [kollerlukas/Camera-Roll-Android-App#13]
Some options are already at the bottom: info, share, edit, delete.

I think these options should be removed from the overflow menu, and maybe add some others like: rotate, flip and rename.

Thanks in advance.

**Comment by kollerlukas** [comment]
I removed info, share, edit, delete from the overflow menu.
In the future I will eventually add more options.

**Comment by jahirfiquitiva** [comment]
@kollerlukas  Great, thank you
