### ISSUE TITLE
After delete confirmation return to next photo

### ISSUE THREAD

**Issue by arvind-gr** [kollerlukas/Camera-Roll-Android-App#132]
Once a photo from filmstrip is deleted, view returns to folder. Also some sort of Recycle bin if implemented will be much helpful...

**Comment by fredgolightly** [comment]
Definitely needs to return to next photo after deleting one

**Comment by kollerlukas** [comment]
Don't know why this to me so long...

**Comment by arvind-gr** [comment]
Thanks for fixing it! Last update v1.0.4 was from 29 Nov 2017.. Is there any closed beta to try this fix?
