### ISSUE TITLE
Bug while applying wallpaper

### ISSUE THREAD

**Issue by shadowbone94** [kollerlukas/Camera-Roll-Android-App#133]
While setting wallpaper from within the app or otherwise, not only is the wallpaper not set (only a black screen) but also the wallpaper is only seen as long as the screen is tapped. Hence there is a glitch like effect.

**Comment by kollerlukas** [comment]
What Android device and version are you on?

**Comment by shadowbone94** [comment]
@kollerlukas 
Device : Moto g(2015) osprey
OS : cm13 with signature spoof
May not be relevant but I do have xposed running.

**Comment by kollerlukas** [comment]
I am sorry but I can't reproduce the issue. Since you are running a custom rom and xposed its possible the issue is related to that.
