### ISSUE TITLE
Basic edit, rotate needed

### ISSUE THREAD

**Issue by fredgolightly** [kollerlukas/Camera-Roll-Android-App#134]
As title, a simple crop or rotate feature - lossless if possible for rotate ie via flags, would be great!

**Comment by alexanderadam** [comment]
There is already issue #109 for image rotation

**Comment by kollerlukas** [comment]
@fredgolightly you can already rotate images via Exif flags throug the ExifEditor.
You can already crop imges with an editor build into Camera Roll. Is it not working for you?

**Comment by fredgolightly** [comment]
@kollerlukas Amazing, thanks for incorporating this, it's incredibly useful, actually better than rotating pixels, I love it!
