### ISSUE TITLE
How to set path of a single Album folder 

### ISSUE THREAD

**Issue by sankar2389** [kollerlukas/Camera-Roll-Android-App#136]
I'm doing a gallery view for a custom Camera App. For which I want to add a gallery view for single album folder. How to achieve this using this code? Where to set path? I found that nested Recyclerview starts with Albums<->Album<->Image. But I need Album->Image

**Comment by kollerlukas** [comment]
Where do you want to have Album displayed (in the MainActivity or in the AlbumActivity)?

**Comment by sankar2389** [comment]
Main Activity

**Comment by kollerlukas** [comment]
Probably the easiest Way to do this is to exclude all Paths except the Path you want to display, or alternativly you could change the MediaProvider, and - Retriever.

Then in the MainActivity it should just work setting the RecyclerViewAdapter to the Album-RecylerViewAdapter and the LayoutManager to a GridLayoutManager with the ColumnCount.

**Comment by kollerlukas** [comment]
@sankar2389 If you wait a couple of days, I will push a commit where I did a little bit of clean up around the RecyclerViewAdapers.

**Comment by sankar2389** [comment]
@kollerlukas Thanks

**Comment by sankar2389** [comment]
@kollerlukas I excluded all other paths, But modifying MainActivity code is little bit complex for me. Can u guide me how to directly open the album in AlbumActivity. So that I could able to change Manifest file to set the AlbumActivity as Launcher?

**Comment by sankar2389** [comment]
@kollerlukas  I found 

//load album
        String path;
        path = Environment.getExternalStorageDirectory().getPath().toString().trim() + "/" + "FOLDER_NAME";
       /* if (savedInstanceState != null && savedInstanceState.containsKey(ALBUM_PATH)) {
            path = savedInstanceState.getString(ALBUM_PATH);
        } else {
            path = getIntent().getStringExtra(ALBUM_PATH);
        }*/

Thanks Again.

**Comment by kollerlukas** [comment]
https://github.com/kollerlukas/Camera-Roll-Android-App/commit/c0f2802e0f8914f238a9cae5844c7bbbdffac57b
Just pushed the cleanup.
If you set 
`public boolean noFolderMode() {
        return false;
 }` 
to `true`, all Albums will be combined into one Album and displayed in the MainActivity.
And if you now exclude the paths you don't want you should be good.
