### ISSUE TITLE
Crash when deleting last item in folder

### ISSUE THREAD

**Issue by mioux** [kollerlukas/Camera-Roll-Android-App#138]
When I delete the last item in a folder, the app crashes (I have the «the application has crashed. Reopen ?» dialog. Or something approaching :smile:)

I use a nexus 5 on lineageos 14.1 nightly builds.

**Comment by kollerlukas** [comment]
That's weird. After some quick testing on my Google Pixel I couldn't reproduce your issue.
Where are you deleting the image from? (AlbumActivity, ItemActivity, ...)

**Comment by kollerlukas** [comment]
I am sorry, but I am unable to reproduce the issue.
I tested this on Google Pixel (8.1), Nexus 5 (6.0.1), Moto X 2014 (Lineage OS 14.1)

**Comment by mioux** [comment]
Sorry for not giving response. I had the bug on ItemActivity, but I think it was a bug in Lineage, as it never re-happened after some system uptades
