### ISSUE TITLE
Sometimes resuming app does not work properly

### ISSUE THREAD

**Issue by jahirfiquitiva** [kollerlukas/Camera-Roll-Android-App#14]
After resuming app, if in picture detailed view, the picture is gone, so only black background is visible. One cannot swipe to other picture, and pressing back button/arrow makes the app crash.

**Comment by jahirfiquitiva** [comment]
Also, after reopening the app, it doesn't load anything, and I had to press refresh option.

**Comment by kollerlukas** [comment]
Can you send me a report, when the app crashes the next time?

**Comment by jahirfiquitiva** [comment]
@kollerlukas Already did

**Comment by kollerlukas** [comment]
Thanks! I will look into this issue.

**Comment by kollerlukas** [comment]
Should be fixed now.
https://github.com/kollerlukas/Camera-Roll-Android-App/commit/49b782163810256114e52a5f038ceda4b6d9771f
