### ISSUE TITLE
Traditional Chinese regions support

### ISSUE THREAD

**Issue by Jahhow** [kollerlukas/Camera-Roll-Android-App#141]
The current folder name "values-zh" cause ignorance in Traditional Chinese regions.

**Comment by Jahhow** [comment]
Found that using folder name "values-zh-rtw" then could made it displayed in

- (Traditional Chinese) Taiwan
- (Traditional Chinese) Hong Kong
- (Traditional Chinese) Macau

And I'm willing to provide Traditional Chinese version.

**Comment by Jahhow** [comment]
Here is the translated XML
[values-zh-rtw.zip](https://github.com/kollerlukas/Camera-Roll-Android-App/files/1762369/values-zh-rtw.zip)

**Comment by kollerlukas** [comment]
Thanks!
https://github.com/kollerlukas/Camera-Roll-Android-App/commit/75c0beac94e7438369c2beebe5680a681235c9ba
