### ISSUE TITLE
more compact folders list when moving photos 

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [kollerlukas/Camera-Roll-Android-App#147]
Hi,

I take quite a lot of pictures and several times a day I have to move some of them to the appropriate folder.

After selecting a photo and taping "move" I have to horizontally scroll the list of folders to select the one I want.

I find this "horizontal scroll" kind of UI really impractical on my phone (Samsung s5) because it only displays two folders at once and I regularly have to scroll to the last one.

Don't you think a more "grid like" UI might be better? It would be faster and easier to find the folder.

Thanks for considering this, great great app of far :)

**Comment by kollerlukas** [comment]
I like the idea. I will come up with something

**Comment by kollerlukas** [comment]
![screenshot_20180309-153543](https://user-images.githubusercontent.com/16599370/37212583-b07799a4-23af-11e8-89a7-711c2e49a9bf.png)
What do you think?

**Comment by thiswillbeyourgithub** [comment]
Oh wow Vielen Dank for such german efficiency :)
