### ISSUE TITLE
[Feature Request] Navigate between picture previews without swiping effect

### ISSUE THREAD

**Issue by eauchat** [kollerlukas/Camera-Roll-Android-App#155]
In picture preview page (one full screen image), swiping left/right to go to next/previous picture is standard, good, and intuitive.
However, I think it would be a real plus to have the possibility to also go to next/previous image without swiping effect. It would facilitate comparison for very similar images, if the images changed without any animation.

I imagine there could be a slideshow mode for example, in which images change from simply tapping in the left or right part of the screen (lots of browser galleries function this way).

Additionally, such mode could even allow swiping gestures to propose other functionalities like easy tagging, flagging or rating (swipe down to flag red, up for green, left or right could open side menus with tickboxes lists of tags).

**Comment by kollerlukas** [comment]
I already implement an option to turn of the PageTransformer Animation.
https://github.com/kollerlukas/Camera-Roll-Android-App/commit/6b5fbb1c13fd94dd339afaaf946adf95fc5a611c
Expect this feature with the next update

**Comment by eauchat** [comment]
I just installed the latest Camera Roll update from F-Droid, and I was looking into the settings. I found the PageTransformer Animation toggle, but it doesn't seem to allow the feature I described previously.
_(I don't know if that makes any difference, but I'm using Android 7.1.2)_

## **This is how it looks with animations:**
![animation-on](https://user-images.githubusercontent.com/34686393/37985544-abc52a24-3201-11e8-950e-29fa40f482ed.png)
![animation-on](https://user-images.githubusercontent.com/34686393/37985525-a3f06f52-3201-11e8-865d-f2a01af80555.gif)

## **This is how it looks without animations:**
![animation-off](https://user-images.githubusercontent.com/34686393/37985561-bbf6560c-3201-11e8-8da8-3573b63fe77b.png)
![animation-off](https://user-images.githubusercontent.com/34686393/37985574-c7a9e248-3201-11e8-8427-5df9fcdb00b5.gif)

## **This is how would be the intended feature I was describing:**
![intended](https://user-images.githubusercontent.com/34686393/37985613-e7a14122-3201-11e8-898e-f1200f5e6d71.gif)

**Comment by eauchat** [comment]
Do you think you could reopen this issue then? Or I can also post a new one?

**Comment by kollerlukas** [comment]
@eauchat Please open a new issue for that, because as far as I understand you, you would like to have a slideshow feature.
