### ISSUE TITLE
Horrible black gabs/borders around images

### ISSUE THREAD

**Issue by fredgolightly** [kollerlukas/Camera-Roll-Android-App#157]
I'm guessing a ui update not error, but the gaps/boarders don't look very nice tbh, the gapless/minimal was way nicer. Could this he reverted?
Love the exif page update, thanks!

**Comment by kollerlukas** [comment]
You mean the wider borders around the images in the AlbumActivity?

**Comment by fredgolightly** [comment]
yep :) just an aesthetic preference

On 25 Mar 2018 10:38 am, "Lukas Koller" <notifications@github.com> wrote:

You mean the wider borders around the images in the AlbumActivity?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/kollerlukas/Camera-Roll-Android-App/issues/157#issuecomment-375957428>,
or mute the thread

**Comment by kollerlukas** [comment]
Actually the wider borders are intensioal. I wanted to give the images more separation.
You don't like them?

**Comment by fredgolightly** [comment]
I much prefer the old, almost gapless way, but it's up to you. I thought it made it more about the images tan the layout.

**Comment by lologolo** [comment]
@kollerlukas i think that the borders aren't fine

**Comment by GoTeamAnt** [comment]
And I like the borders.

I guess we need a setting for this now.
