### ISSUE TITLE
When wanting to attach pictures app does not appear as an option.

### ISSUE THREAD

**Issue by jahirfiquitiva** [kollerlukas/Camera-Roll-Android-App#16]
When trying to pick pictures to send via Messenger Lite, the app just doesn't show to pick the picture from it.

Other apps where the gallery does not appear as an option:
1. Trying to pick an icon from gallery to set a custom icon for an app in Nova Launcher.
2. File manager (when an app opens the default internal file manager). (Happened only when opened from Twitter or Google Keep or Todoist).

Please look into it. Thanks

**Comment by kollerlukas** [comment]
Oh. Thanks for letting me know.
I was missing this category in my intent filter in my manifest:
<category android:name="android.intent.category.OPENABLE" />
