### ISSUE TITLE
Style problem

### ISSUE THREAD

**Issue by tanrak** [kollerlukas/Camera-Roll-Android-App#160]
Hi, good work your gallery app but in version 1.0.5 the card2 style is the same as card style. In version 1.0.4 it was correct. This problem exists in Google Play and Izzy repo.

**Comment by kollerlukas** [comment]
They should be the same. But they look pretty similar. It is easier to see in the light theme, that the cards style has rounded corners and the cards are elevated.

**Comment by tanrak** [comment]
Ok, i understand what you mean but for me the old variant with no gap (style2) was better. But no problem. It's not the end of the world. I close this issue.
