### ISSUE TITLE
Camera Roll: Move and Copy features crashes the app

### ISSUE THREAD

**Issue by Godwyyn** [kollerlukas/Camera-Roll-Android-App#166]
#### Expected behavior
After viewing a file,when I want to copy or move the file from one location to another I expected the app to do so successfully without crashing.

#### Actual behavior
When I view a file, click on the menu option and select either copy or move, then select the destination folder and click on the "Ok" button the app crashes.

#### How to reproduce
- Download the Camera Roll app from playstore
- Launch the app
- Select a file to view it
- When viewing the file,click on the menu icon to view the drop down options
- Click on Copy or Move
- Select the destination Folder
- Click on the "Ok" button

* Version: Veersion 1.0.5
* Operating system: Infinix Hot, Android Kitkat

#### Recording Of The Bug
https://www.youtube.com/watch?v=-O-Oft0HPeI
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@godwyn/camera-roll-move-and-copy-features-crashes-the-app">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by kollerlukas** [comment]
I the bug is probably related to the rename bug/crash (#165)
