### ISSUE TITLE
List HomeScreen Style

### ISSUE THREAD

**Issue by Edfgdz** [kollerlukas/Camera-Roll-Android-App#168]
Can you make this app homepage display photos in this way?
At present,photos is displayed too large.

![img_20180401_124610](https://user-images.githubusercontent.com/26460124/38169928-ace36ba8-35aa-11e8-84ac-4ed4849fb544.jpg)

**Comment by Edfgdz** [comment]
Hello,i want to contact you through email for this app development.
But the email address left at google play not work.

How can i contact you?

**Comment by kollerlukas** [comment]
lukaskoller6@gmail.com is my email adress.

**Comment by Edfgdz** [comment]
I have sent email to you,wish you can reply to me.
