### ISSUE TITLE
Camera Roll: Bug found when clicked on "Scan"

### ISSUE THREAD

**Issue by Godwyyn** [kollerlukas/Camera-Roll-Android-App#169]
#### Expected behavior
After navigating  to the storage folder by clicking on the "File Explorer" option, I expected the app  to scan the storage folder for files and probably display them.

#### Actual behavior
When I get to a folder in my storage that I want to scan and then clicked on "Scan" option the app crashes and takes me back to the Home Activity.

#### How to reproduce
 -  Download the Camera Roll app from Playstore
 -  Launch the app
 -  At the home activity, Click on the menu option icon at the top right
 -  From the menu options click on "File Explorer"
 -  Navigate to a folder you want to scan
 -  Click on the menu icon 
 -  From the drop down options click on "Scan"
 -  The app crashes and returns to the Home Activity.

* App Version: Version 1.0.5
* Operating system: Infinix Hot, Android Kitkat

#### Recording Of The Bug
https://www.youtube.com/watch?v=L1VpCrh5z_M
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@godwyn/camera-roll-bug-found-when-clicked-on-scan">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by kollerlukas** [comment]
Found the issue: When you are trying to scan a huge directory, retrieving all the children dirs is done on the MainThread.
