### ISSUE TITLE
Camera FAB click not working

### ISSUE THREAD

**Issue by jahirfiquitiva** [kollerlukas/Camera-Roll-Android-App#17]
Only the animation is shown.
Using a Moto G5 Plus.

**Comment by kollerlukas** [comment]
What Camera Apps do you have installed on your device?

**Comment by jahirfiquitiva** [comment]
* Motorola Camera
* Google Camera
* OnePlus Camera

**Comment by kollerlukas** [comment]
Weird. I just tryied it on my Google Pixel, Moto X (2.gen), Nexus 5 & 4, and Samsung S7, and it work on all of them.
Is your phone rooted and/or are you running a custom rom?

**Comment by jahirfiquitiva** [comment]
Not rooted and not using any custom rom

**Comment by kollerlukas** [comment]
I am sorry I tried everthing I can think of, but I can't repoduce your issue. Do you by any change have a second or other android phone?

**Comment by jahirfiquitiva** [comment]
@kollerlukas 

I tried on my old Moto G 2nd Gen and it worked. It has Android 7.1.2 using LineageOS and only Google Camera installed.

This is something weird indeed, but maybe you can add another method to get the default camera, or show a bottom sheet like this one to choose the default camera to launch from FAB.

![screenshot_20170513-194228](https://cloud.githubusercontent.com/assets/10360816/26030304/48ab48f6-3815-11e7-9b06-c61554a9babd.png)

**Comment by HeyItsJono** [comment]
I'm also unfortunately having this issue on a Stock Unrooted 7.1.2 Nexus 6P. Button will just play the animation. My camera apps:

- Google Camera
- Snapchat
- Manual Camera
- VSCO

**Comment by kollerlukas** [comment]
Found the issue: Shortcut only works when a default camera app is set. Will fix this as soon as possible.

**Comment by kollerlukas** [comment]
https://github.com/kollerlukas/Camera-Roll-Android-App/commit/49b782163810256114e52a5f038ceda4b6d9771f
