### ISSUE TITLE
Bug: cropping screen very slow, and hard to use 

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [kollerlukas/Camera-Roll-Android-App#170]
Suppose you take this photo (download it first, of course) :

http://img.gawkerassets.com/img/18tbvl3htulmyjpg/original.jpg

And you try to crop it.

Not only it is very hard to change the size of the cropping rectangle, but even when you do succeed, it's very hard to move its corners, and it's also very slow while doing it .

See video:
https://ufile.io/1xk30

The version of this is from the Play Store.

**Comment by AndroidDeveloperLB** [comment]
@kollerlukas I don't understand. Why close it?
Was it fixed?

**Comment by kollerlukas** [comment]
Yeah! I fixed it with this commit https://github.com/kollerlukas/Camera-Roll-Android-App/commit/f9773d8361b402fd987f7ea147b902445b1d687d

**Comment by AndroidDeveloperLB** [comment]
Will cloning the project have this fix?

**Comment by kollerlukas** [comment]
Yes

**Comment by kollerlukas** [comment]
You just have to build the apk yourself

**Comment by AndroidDeveloperLB** [comment]
Doesn't work. I get this error:

![image](https://user-images.githubusercontent.com/5357526/38322416-02272b14-3843-11e8-8b73-3f75813a6e06.png)

**Comment by AndroidDeveloperLB** [comment]
I also don't see it on the Play Store.

**Comment by kollerlukas** [comment]
@AndroidDeveloperLB  It seems like your Android SDK isn't configured correctly. Check your SDK location under Settings (see screenshot)
<img width="1213" alt="unbenannt" src="https://user-images.githubusercontent.com/16599370/38324413-88c0e866-3840-11e8-9104-09aeca21b9ba.PNG">

I have not yet released the update, that's why the PlayStore version still has the bug.

**Comment by AndroidDeveloperLB** [comment]
Since I can import and create projects already, I think it's not an issue on my configuration, which seems like on your case:

![image](https://user-images.githubusercontent.com/5357526/38325035-89a5277e-384a-11e8-9b38-5f5d11ad4bd5.png)

**Comment by kollerlukas** [comment]
That's wierd. The projects builds just fine on my end.

Here the debug apk for you to test.
[Camera Roll Debug apk.zip](https://github.com/kollerlukas/Camera-Roll-Android-App/files/1876956/Camera.Roll.Debug.apk.zip)

**Comment by AndroidDeveloperLB** [comment]
I think this is the issue, which is the project properties :

![image](https://user-images.githubusercontent.com/5357526/38325164-e4af9406-384a-11e8-8778-0d70533dfafb.png)

Should be as such:

![image](https://user-images.githubusercontent.com/5357526/38325185-f6485d88-384a-11e8-99f3-8066e5096a12.png)

And then I chose to sync with gradle files.
Please update your project. Maybe you need to also exclude some temporary folders, such as the gradle folder, from the repository.
You should also remove the "buildToolsVersion" configuration, because this is set automatically anyway to the latest version.

After all of those things I've written, it works fine. Is there a way maybe to change the way the cropping rectangle moves? Meaning that when you drag it, the rectangle should move to where you drag it. In the current configuration, it's the opposite, as it moves the entire image instead.

Also, Why does it get so blurry compared to the gallery app? I know it's for memory optimizations, but still. It occurs a lot, and with a much more intense blur effect...
