### ISSUE TITLE
Apps crash when i try to delete some image in Camera roll application

### ISSUE THREAD

**Issue by abdulmalikkhan655** [kollerlukas/Camera-Roll-Android-App#175]
#### Expected behavior
According to my knowledge, when I sort out a folder and delete it, the folder will be deleted And that folder will always remove from my mobile phone forever

#### Actual behavior
when i select the image   click on delete button apps is crash  you can see in bug video 

#### How to reproduce
* [download ](https://f-droid.org/packages/us.koller.cameraroll/)and install the application
* open the application select the image you want yo delete 
* click on delete button 
* note Bug 
* Browser: Camera Roll - Gallery Version v1.0.5
* Operating system: android version 4.4.2
* smart phone GALAXY Note 3

#### Recording Of The Bug
https://youtu.be/a5ANnrBZo_E
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@abdulmalikkhan/apps-crash-when-i-try-to-delete-some-image-in-camera-roll-application">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by tobias-g1** [comment]
I was also able to replicate this issue on 4.4.2, I wasn't able to replicate this issue on 5.0.2 I thought this could potentially be related to the can't delete a photo in folder bug mentioned previously within your closed issues, however this particular bug seems to occur for all photos within a folder so don't believe this is related. If you need any help finding the issue or further clarification I'd be happy to help. 

Thanks,
Tobias
_Utopian.io Moderator_

**Comment by kollerlukas** [comment]
Probably the same issue as #165, #166, #167 & #169

**Comment by kollerlukas** [comment]
Was this fixed with the last update?
