### ISSUE TITLE
[enhancement] Sort album/folder screen by most recent additions

### ISSUE THREAD

**Issue by HeyItsJono** [kollerlukas/Camera-Roll-Android-App#18]
Hey there, just wanted to say that this app is incredible - hands down the prettiest gallery app on Android! I was wondering if you'd consider implementing a new sort option so that albums/folders that have most recently had a photo added to them appear at the top of the list (similar to how Google Photos alters its album quick-list). Basically sorting by most recent additions so albums that haven't had anything added to them for a long time also end up appearing on the bottom. 

I know you get a tonne of feature requests so completely fair if you don't want to add it, but it'd be an awesome feature to have.

Thank you! 😄

**Comment by kollerlukas** [comment]
Sure!

**Comment by kollerlukas** [comment]
https://github.com/kollerlukas/Camera-Roll-Android-App/commit/49b782163810256114e52a5f038ceda4b6d9771f

**Comment by HeyItsJono** [comment]
Thanks so much!
