### ISSUE TITLE
Configuring a negative number of columns for cards view crashes app on startup

### ISSUE THREAD

**Issue by ChristianCiach** [kollerlukas/Camera-Roll-Android-App#188]
As the title says, configuring a negative number of card columns shouldn't be allowed to prevent a crash. Also, there should probably be an upper limit of columns :)

**Comment by eauchat** [comment]
Please do not set an upper limit of columns. Or if you do, make it really very high. I currently generally use seven or more columns. But I sometimes have use cases where having 20 is actually useful.
The current app supports that and it's awesome.
However, a small comment is that when there are more than 6 columns, the margin between thumbnails gets to be too big compared to the size of the thumbnails (maybe I should open an issue for that, but it's a very little detail in such a great app).
