### ISSUE TITLE
Publish APK on Github?

### ISSUE THREAD

**Issue by IzzySoft** [kollerlukas/Camera-Roll-Android-App#19]
Any chance we can see the `.apk` here at Github, so it can be obtained without access to Playstore? For an easy approach to that, just in case, I might refer to [Creating Releases](https://help.github.com/articles/creating-releases/) in the GitHub Help (basically: just create a tag, push it to Github, attach the `.apk` file to it and optionally a description for the release – done).

Thanks in advance!

**Comment by kollerlukas** [comment]
I just added most of the verisons I uploaded to the playstore.
Thanks!

**Comment by IzzySoft** [comment]
Thanks a lot! You can now also find it [here](https://apt.izzysoft.de/fdroid/index/apk/us.koller.cameraroll) in my F-Droid compatible repo (so users without Playstore can use the F-Droid client to install it and keep it updated). Updates are usually available within 24h of your attaching it to a new tag. Be welcome pointing there as an alternative source!
