### ISSUE TITLE
[Feature Request] Password protected hidden folders

### ISSUE THREAD

**Issue by matt31** [kollerlukas/Camera-Roll-Android-App#192]
One of the only features that I would like to have on this app would be a password to protect hidden folders. It's the only thing really keeping me from using this app as my main gallery app since I have a lot of private photos hidden, and it wouldn't be nice to have someone clicking to show my hidden folders and seeing everything without my knowledge. A simple pin protection would be nice.

**Comment by thiswillbeyourgithub** [comment]
AES encryption for those folders would be nice too, but it's quite a long stretch I think. In the meantime I'm using s.s.e. encryption, open source and cross platform.

**Comment by kollerlukas** [comment]
https://github.com/kollerlukas/Camera-Roll-Android-App/issues/49
