### ISSUE TITLE
new logo  for your application

### ISSUE THREAD

**Issue by abdulmalikkhan655** [kollerlukas/Camera-Roll-Android-App#195]
hello @kollerlukas how are you i hope  you will be fine  i want to make logo for you if you  want logo for your app i will send you my awesome design i hope you like it

**Comment by TacoTheDank** [comment]
just stop already dude you're fucking pathetic

shit ain't even your own design, you take shit straight from flaticon.com

**Comment by kollerlukas** [comment]
@TacoTheDank Do you mean me!?

**Comment by TacoTheDank** [comment]
@kollerlukas no, i mean abdul or whoever

**Comment by TacoTheDank** [comment]
he's going around on various open source android projects spamming this in issues trying to make some crypto with utopian.io

hes not the only one either
