### ISSUE TITLE
Video Playback [Bug]

### ISSUE THREAD

**Issue by TGNYC** [kollerlukas/Camera-Roll-Android-App#2]
Device: OnePlus 3
Android Version: 7.1.1
App Version: 1.3 Beta (15)
-----
The video playback is really buggy. When I tap a video from a folder or swipe to it from a picture, the app takes a lot longer to open than a picture. The video controls are also really bare (there is only play and pause). Rotating the orientation of the device is not seamless, the video goes black for a second, then shifts and is paused. After the video is finished playing, if I hit play again, nothing happens; I expect to replay the video on click. 

I recommend using a different video playback engine or the device's native video playback engine.

**Comment by kollerlukas** [comment]
You also can't replay a video.
Yeah I know the current video solution is not ideal. 
I am currently using a library called ExoMedia.
I will look into ways of improving the video experience.

**Comment by kollerlukas** [comment]
most video issues should be fixed. 
https://github.com/kollerlukas/Camera-Roll-Android-App/commit/aadc6b3f82741b9c4cd1048125d2cf862c7b8dc8
