### ISSUE TITLE
Long folder names on NestedRecyclerView

### ISSUE THREAD

**Issue by cocobelgica** [kollerlukas/Camera-Roll-Android-App#20]
Perhaps wrap or shorten(w/ ellipses) long folder names. See screenshot below:

![Long Folder Name](https://i.imgur.com/lXAkDER_d.jpg?maxwidth=640&shape=thumb&fidelity=high)

**Comment by kollerlukas** [comment]
Should be fixed now. I am using `android:ellipsize="end"`.
https://github.com/kollerlukas/Camera-Roll-Android-App/commit/f0e9368001d1e17a6962c2306f67ed73def76c28
