### ISSUE TITLE
Wrong picture picked when sharing

### ISSUE THREAD

**Issue by Fran5ois** [kollerlukas/Camera-Roll-Android-App#201]
Hello,

First of all many thanks for this app, I love it.

Hoping it might help, here is a bug I noticed:

After hiting the "share" icon on a picture I just took, I then choose the mean of sharing (email in my case), then another picture is displayed. I have to go back, pick again the correct picture and share it.

Also I find the time a little long after hiting the "share" button before all the possible sharing options are displayed on a whole new screen... I liked the way quickpic worked for that matter: a small unfolding menu with few sharing options that I usually choose.

Again many thanks

**Comment by kollerlukas** [comment]
https://github.com/kollerlukas/Camera-Roll-Android-App/issues/135
