### ISSUE TITLE
Allow only specific folders

### ISSUE THREAD

**Issue by weberjn** [kollerlukas/Camera-Roll-Android-App#207]
Camera Roll has a setting to exclude folders.

There should also be a setting to allow only the given folders, so folders would be forbidden by default and one would not have to add another exclusion after creating a folder.

* Included folders
* Excluded folders

Folders shown are:

    if included set:
        included folders minus excluded
    else:
        all folders minus excluded

**Comment by IzzySoft** [comment]
Duplicate of #142 (sorry).
