### ISSUE TITLE
Add FAQs

### ISSUE THREAD

**Issue by HarryHeights** [kollerlukas/Camera-Roll-Android-App#213]
Hello, I'm Harry. 
I mostly contribute to open source projects as a copywriter. This is creating documents which I feel are essential to that particular project. Having a FAQs document for camera roll will be awesome and I could compile a couple of questions and answers I think have high probability of being asked by new end users and even existing users. 

Would love to know your thoughts on this.

**Comment by HarryHeights** [comment]
Yea it could. I'll await his reply to his thoughts on this

**Comment by kollerlukas** [comment]
I think its a great idea. I just created a wiki page for that. @IzzySoft I have never used a Wiki before. Can you edit pages on the wiki and create a pull request? That would be great. Thanks in advance for all your help!

**Comment by IzzySoft** [comment]
@kollerlukas unless you "lock it down", everybody with a valid Github account can edit it online (using a web browser). As the wiki is stored in its own Git repo, you can

* clone that to keep a local copy
* revert any changes you don't like
* give dedicated users access to that Git repo (wiki) so they can edit it locally

Haven't tried the third bullet point (not sure if permissions are bound to the main repo), but use it that way for some of my own projects (being the only one with write access to the wiki there). Not sure how PRs work on wiki (never tried that) – but being a Git repo of its own, it should somehow be possible. What's unclear is how to open a PR there … so the alternative might be sending patches via the issue tracker. Maybe. Though that would be far from being optimal.

**Comment by HarryHeights** [comment]
@izzysoft, the whole wiki thing is a bit confusing for me as I'm not a developer and not so knowledgeable around Github environment. How about I create a PR of the FAQs document and then you find a way to place it in the wiki  section. It wouldn't fair badly in the master branch though. or what do you think @kollerlukas ?

**Comment by IzzySoft** [comment]
@HarryHeights 

> the whole wiki thing is a bit confusing for me as I'm not a developer and not so knowledgeable around Github environment

Then it's perfectly fitted for you as you can simply use the online editor in a web browser. A little basic knowledge in Markdown formatting would be helpful. The other features I mentioned you can simply ignore; they might be nice for Lukas, or other contributors.

A PR would go against the main repo, which doesn't make much sense as it never could be merged there. Though if Lukas likes the idea, the associated branch could be pulled locally, the file be copied over, and committed to the wiki repo. But while that might work fine for initial creation of a file, it might become a mess with updates, not trivial to handle.

As said, let Lukas decide (meanwhile, you could check out the editor in the wiki to see if it fits you; as long as you never hit "save", no changes are done – and if you hit it, they can be reverted anytime).
