### ISSUE TITLE
8 bit color option cutoff at the bottom of the screen

### ISSUE THREAD

**Issue by anzetal** [kollerlukas/Camera-Roll-Android-App#219]
Redmi note 4
Lineage OS 15.1
Camera Roll version 1.0.6
![screenshot_camera_roll_20180921-132807](https://user-images.githubusercontent.com/35098870/45868185-b98a4b80-bda2-11e8-9518-b31cbc1676af.png)

**Comment by lologolo** [comment]
@anzetal i have the same problem

**Comment by kollerlukas** [comment]
duplicate to #211
