### ISSUE TITLE
Inability to zoom on first view

### ISSUE THREAD

**Issue by HeyItsJono** [kollerlukas/Camera-Roll-Android-App#22]
Hey there!
I've noticed a very small issue; upon first viewing or swiping to an image, if I try and double-tap or pinch-out to zoom into the photo, I can't zoom. However, if I swipe to another photo, then swipe back to the initial one, double-tapping/pinching-out works and allows me to zoom!

**Comment by kollerlukas** [comment]
I am sorry, but I am unable to recreate your issue.
What Android verison and device are you running?

**Comment by HeyItsJono** [comment]
Nexus 6P - Stock 7.1.2
I just tried again and realised it only seems to happen on really big image files, so maybe it was just because the pictures hadn't been completely loaded in!

**Comment by kollerlukas** [comment]
How big are the pictures?

**Comment by HeyItsJono** [comment]
The images were around 5MB each. Oddly, I just tried to recreate the issue myself and couldn't - maybe my phone was just being weird/laggy at the time. Sorry!
