### ISSUE TITLE
Not possible to make an excluded folder visible again

### ISSUE THREAD

**Issue by alsido** [kollerlukas/Camera-Roll-Android-App#225]
There is no way to make an excluded folder visible again.
v.1.0.6.

**Comment by kollerlukas** [comment]
In the settings under "Excluded Paths" you can exclude and un-exclude any path on your phone.

**Comment by alsido** [comment]
Only unchecked phone root folder (and SD-card root, if availbale) listed there. 

But manually excluded folder are not listed. So it is not possible to get them back.

Tested on four devices: Android 4.4.2, 6.0, 7.1, 8.0 and in Android Studio emulator.

**Comment by kollerlukas** [comment]
This is like a file explorer, you can click on the phone root folder to view the subfolders of the phone root folder. And somewhere (what ever path you excluded) there you should find your excluded folder.
