### ISSUE TITLE
NFC support 

### ISSUE THREAD

**Issue by ByteHamster** [kollerlukas/Camera-Roll-Android-App#228]
It would be nice to have support for NFC file beaming. Currently, tapping the phones together just opens the Google Play page of Camera Roll.

**Comment by kollerlukas** [comment]
I am sorry, but I don't think this should be a feature provided by a thrid party gallery app.

**Comment by ByteHamster** [comment]
Why not? This is exactly what I would expect from a Gallery app. Just like Google Photos and the stock gallery app beam the current photo when tapping the devices together.

**Comment by kollerlukas** [comment]
I think this is a pretty advanced feature I haven't felt missing yet. And since it's just me struggling to find time to continue to work on Camera Roll I don't think this a feature I can tackle in the nearer future. I am sorry.

**Comment by ByteHamster** [comment]
Sending files with Android Beam seems to be as simple as returning the URI of the current image in a callback function. Would you accept a PR that adds NFC functionality?

https://developer.android.com/training/beam-files/send-files#java
