### ISSUE TITLE
Release cached images when deleted/missing

### ISSUE THREAD

**Issue by fredgolightly** [kollerlukas/Camera-Roll-Android-App#229]
I've indexed and viewed 100s of dslr shots on my tablet via Camera Roll, but even after deleting them the apps cached data is still huge ie includes them. Clearing cache after removing the images indexes everything else and doesn't obviously include these thumbnails.

Would it be possible to discard the cache when images are removed?

**Comment by kollerlukas** [comment]
Just go into the app-details page and clear the cache there.

**Comment by fredgolightly** [comment]
That's what I do, but it should release/clear them as soon as it realises they're gone without going into the app settings and doing this manually.

**Comment by kollerlukas** [comment]
I am using the Glide image loading library to show and cache image. I do not have any control over the cache. I can only invalidate the cache, but the cache is only cleared, when you manually clear it or the OS need memory space.
