### ISSUE TITLE
Select All option

### ISSUE THREAD

**Issue by Primokorn** [kollerlukas/Camera-Roll-Android-App#24]
Hi,
It seems we have to select files one by one.
An option to select them all would be appreciated.
Thank you.

**Comment by cocobelgica** [comment]
Perhaps drag>select ala Google Photos (and I believe QuickPic) can be added as well.

**Comment by kollerlukas** [comment]
DragSelect is already possible

**Comment by cocobelgica** [comment]
Oh, didn't notice it previously, perhaps I tested it on the NestedRecyclerView. Cool to know that it's already possible

**Comment by Primokorn** [comment]
The DragSelect option is awesome (thanks for the tip) but not handy when all files don't appear on one screen.
