### ISSUE TITLE
More information about a selected file

### ISSUE THREAD

**Issue by Primokorn** [kollerlukas/Camera-Roll-Android-App#25]
Hi,
After selecting a file, could you add an option to get more information? (e.g patch, size, dimensions,...)
Thank you.

**Comment by kollerlukas** [comment]
Do you want an option to get information on selected files (when you are selecting them in the Album view)?

**Comment by Primokorn** [comment]
Yes, something like this:
![screenshot_20170602-094034](https://cloud.githubusercontent.com/assets/5938828/26715895/a64c35c6-4777-11e7-8700-a55e8da9d72f.png)

**Comment by kollerlukas** [comment]
You can already get information about filepath, size, dimensions, ... , when you hit the info button in the image View.
![screenshot_20170602-004320](https://cloud.githubusercontent.com/assets/16599370/26716053/d9cd3c60-472c-11e7-85f5-958afd572939.png)

**Comment by Primokorn** [comment]
My bad... I was searching from the 3 dots menu.
Thank you.

**Comment by Primokorn** [comment]
Could you move the information option on the actionbar or in the 3 dots menu?

I can't open this file so I can't know where it is stored.

![capture](https://user-images.githubusercontent.com/5938828/27169053-7d6fd064-51a8-11e7-8a98-4db4b439d076.PNG)

**Comment by kollerlukas** [comment]
I now made it possible to open broken files.

**Comment by kollerlukas** [comment]
Would this fix your issue?

**Comment by Primokorn** [comment]
Yes. I keep the file until the next update.

**Comment by kollerlukas** [comment]
Fixed now?

**Comment by Primokorn** [comment]
Oh yes, thanks.
