### ISSUE TITLE
"Home Page" listed on F-Droid: 404 Error

### ISSUE THREAD

**Issue by Grossdm** [kollerlukas/Camera-Roll-Android-App#252]
Hello,

I found your app on F-Droid.

I don't know if the listed Home Page is affected everywhere it may be listed, but in its F-Droid listing the [Camera Roll Homepage](http://lukas.koller.us/) yields a GitHub styled 404 Error.

Thank you.

**Comment by kollerlukas** [comment]
I changed my domain to koller.app

**Comment by IzzySoft** [comment]
[Fixing](https://gitlab.com/fdroid/fdroiddata/merge_requests/4695)… Should be corrected with the next index update, hopefully.

**Comment by Grossdm** [comment]
It is fixed - I just loaded the homepage a moment ago.
