### ISSUE TITLE
Inconsistent ellipses on folder names

### ISSUE THREAD

**Issue by cocobelgica** [kollerlukas/Camera-Roll-Android-App#26]
I noticed that even short folder names such as "Screenshots" are at times getting shortened and at other times not. See pic below for reference:

![foo](http://i.imgur.com/yLKOVIN.jpg)

**Comment by jerryn70** [comment]
In cards view and card view 2 some folder name is not showing fully. Some folder name that has 8 to 9 characters are fully showing and folders names that has only 3 to 4 characters are not showing.

**Comment by kollerlukas** [comment]
Should be all fixed now.
Problem was TextView didn't change its size, when new Albumname was set.
https://github.com/kollerlukas/Camera-Roll-Android-App/commit/fbbee8b9e98eadc40092465d3dc4a1b8344795f8
