### ISSUE TITLE
MKV format video is not showing in Gallery

### ISSUE THREAD

**Issue by jerryn70** [kollerlukas/Camera-Roll-Android-App#27]

**Comment by kollerlukas** [comment]
Is it a regular .mkv file?

**Comment by jerryn70** [comment]
Yes . All other Gallery app shows that . 
I enabled media retriever option but still it's not showing.

**Comment by kollerlukas** [comment]
Is the file on a removable sd card?
Maybe is the folder excluded or hidden?

**Comment by jerryn70** [comment]
Yes it on sd card. 
No it's not hidden or excluded.

**Comment by jerryn70** [comment]
I tried 'open with camera roll' using file manager, then I got a error toast message.

**Comment by kollerlukas** [comment]
Have you tried to open a picture that is in the same directory as the mkv video?

**Comment by jerryn70** [comment]
Just "error" that was the message. 

Yes I have tried There is no problem with images.

**Comment by kollerlukas** [comment]
Have you tried to copy the video to another location and open it from there?

**Comment by jerryn70** [comment]
I found the issue. The format was .Mkv and I  renamed it to .mkv . now it is showing in Gallery and I can play that video. 

But it's strange that all other Gallery app detects .Mkv and .mkv . But yours  only detects .mvk

**Comment by kollerlukas** [comment]
I know why, because I am only checking of ".mkv". But I will probably change that.
