### ISSUE TITLE
Wrong Cover Image

### ISSUE THREAD

**Issue by jerryn70** [kollerlukas/Camera-Roll-Android-App#29]
Wrong Cover image is displayed. In screenshot you can see the latest image is not displayed as the cover image. 
![screenshot_20170605-123010](https://cloud.githubusercontent.com/assets/23030460/26774882/06226662-49f0-11e7-9b8f-bc3677c616a6.png)
![screenshot_20170605-122959 01](https://cloud.githubusercontent.com/assets/23030460/26774892/1441d002-49f0-11e7-9b8c-a8b6d1abdeee.png)

**Comment by jerryn70** [comment]
Enabling Media Retriever will fix this issue but then it leads to issue #32

**Comment by kollerlukas** [comment]
Issue should be fixed now. It had to do with the albums not being sorted correcly, when items had the same date.
https://github.com/kollerlukas/Camera-Roll-Android-App/commit/dabfdfcf93921a3d1a4fee77fe3c1403bfaad1b2
