### ISSUE TITLE
Metadata Editor [Feature]

### ISSUE THREAD

**Issue by TGNYC** [kollerlukas/Camera-Roll-Android-App#3]
The app should have a metadata editor or at least a rename image feature.

**Comment by kollerlukas** [comment]
The Metadata Editor is a good idea. I can add the ability to edit Exif-Data from your photos.

**Comment by kollerlukas** [comment]
With the latest commit, I added an Exif Editor. This allows you to edit the Exif Data of photo, e.g. Date, Location, Camera Model, Orientation, ... .

**Comment by kollerlukas** [comment]
https://github.com/kollerlukas/Camera-Roll-Android-App/commit/7a4d366f2dade0fd28ed059c79d2064504fadcde
