### ISSUE TITLE
Excluded Folder shows when Media Retriever is Enabled

### ISSUE THREAD

**Issue by jerryn70** [kollerlukas/Camera-Roll-Android-App#32]
I have enabled media retriever option because some of my folders and images are not properly showing. But when I enable that option it shows excluded folders . See screenshot 
![picsart_06-05-01 58 00](https://cloud.githubusercontent.com/assets/23030460/26776677/c8564bac-49f7-11e7-8ef3-69a8cb208013.jpg)

**Comment by kollerlukas** [comment]
Should also be fixed now.
https://github.com/kollerlukas/Camera-Roll-Android-App/commit/fbbee8b9e98eadc40092465d3dc4a1b8344795f8
