### ISSUE TITLE
Sort by date option (taken date)

### ISSUE THREAD

**Issue by jerryn70** [kollerlukas/Camera-Roll-Android-App#34]

**Comment by kollerlukas** [comment]
Sadly there is no way to get the creation date of a file. I could use the Exif data for that, but Exif is only supported by jpg, and not by png, gif, or any kind of video.
I think using the Exif data for sorting would introduce inconsistency (all gif and videos at the top or bottom).

I would add this feature if I find a way to somehow get the creation date of a file.

**Comment by jerryn70** [comment]
But other Gallery apps have that option. 
Example quickpic and simple gallery .
Simple gallery is an open source project you can look the code they used for date sorting.

**Comment by kollerlukas** [comment]
I now tried to get the date taken from Android MediaStore. This drasically increases loading time (from ~300 ms to ~3500 ms; tested on my Google Pixel). I could try and improve the loading time, but I don't think I can improve it by much.

**Comment by kollerlukas** [comment]
I am now using the DATE_TAKEN value from MediaStore. But I am not happy about it and I am not sure if I will keep it.
The problem:
It works great for pictures and videos taken with the phone, but downloaded the DATE_TAKEN value is essentially the same to File.lastModified(). The result is that downloaded images are just mixed under the images taken on your phone.
And If you look at simple gallery its actually the same problem.

**Comment by jerryn70** [comment]
Thats not a big problem I think. All Gallery apps have that issue when sorting with taken date.  
In every users gallery 90% of images and videos are taken using there phones. So that's not a big issue

**Comment by kollerlukas** [comment]
https://github.com/kollerlukas/Camera-Roll-Android-App/commit/fbbee8b9e98eadc40092465d3dc4a1b8344795f8
