### ISSUE TITLE
Deleted files coming back automatically


### ISSUE THREAD

**Issue by jerryn70** [kollerlukas/Camera-Roll-Android-App#35]
I have deleted few images. After some time I open the Gallery and click refresh button. Then the deleted file came back.

**Comment by kollerlukas** [comment]
What does the Toast say?
Deleting images from a removable sd card doesn't work right now.

**Comment by jerryn70** [comment]
I deleted images in my sd card .

**Comment by kollerlukas** [comment]
https://github.com/kollerlukas/Camera-Roll-Android-App/issues/39

**Comment by kollerlukas** [comment]
#39

**Comment by kollerlukas** [comment]
#39
