### ISSUE TITLE
Crash when launching the app

### ISSUE THREAD

**Issue by Artemka778** [kollerlukas/Camera-Roll-Android-App#38]
Flies right after launch.

Log:
```
06-06 20:28:12.703 E/AndroidRuntime(3193): FATAL EXCEPTION: main
06-06 20:28:12.703 E/AndroidRuntime(3193): Process: us.koller.cameraroll, PID: 3193
06-06 20:28:12.703 E/AndroidRuntime(3193): java.lang.IllegalArgumentException: Failed to find storage device at /storage/emulated/legacy/Download
06-06 20:28:12.703 E/AndroidRuntime(3193): 	at android.os.Environment.isExternalStorageRemovable(Environment.java:963)
06-06 20:28:12.703 E/AndroidRuntime(3193): 	at us.koller.cameraroll.a.d.a.a.a(Unknown Source)
06-06 20:28:12.703 E/AndroidRuntime(3193): 	at us.koller.cameraroll.a.d.a.e.a(Unknown Source)
06-06 20:28:12.703 E/AndroidRuntime(3193): 	at us.koller.cameraroll.a.d.a.a(Unknown Source)
06-06 20:28:12.703 E/AndroidRuntime(3193): 	at android.support.v7.widget.RecyclerView$a.a(Unknown Source)
06-06 20:28:12.703 E/AndroidRuntime(3193): 	at android.support.v7.widget.RecyclerView$a.b(Unknown Source)
06-06 20:28:12.703 E/AndroidRuntime(3193): 	at android.support.v7.widget.RecyclerView$o.a(Unknown Source)
06-06 20:28:12.703 E/AndroidRuntime(3193): 	at android.support.v7.widget.RecyclerView$o.a(Unknown Source)
06-06 20:28:12.703 E/AndroidRuntime(3193): 	at android.support.v7.widget.RecyclerView$o.a(Unknown Source)
06-06 20:28:12.703 E/AndroidRuntime(3193): 	at android.support.v7.widget.RecyclerView$o.c(Unknown Source)
06-06 20:28:12.703 E/AndroidRuntime(3193): 	at android.support.v7.widget.LinearLayoutManager$c.a(Unknown Source)
06-06 20:28:12.703 E/AndroidRuntime(3193): 	at android.support.v7.widget.GridLayoutManager.a(Unknown Source)
06-06 20:28:12.703 E/AndroidRuntime(3193): 	at android.support.v7.widget.LinearLayoutManager.a(Unknown Source)
06-06 20:28:12.703 E/AndroidRuntime(3193): 	at android.support.v7.widget.LinearLayoutManager.c(Unknown Source)
06-06 20:28:12.703 E/AndroidRuntime(3193): 	at android.support.v7.widget.GridLayoutManager.c(Unknown Source)
06-06 20:28:12.703 E/AndroidRuntime(3193): 	at android.support.v7.widget.RecyclerView.O(Unknown Source)
06-06 20:28:12.703 E/AndroidRuntime(3193): 	at android.support.v7.widget.RecyclerView.p(Unknown Source)
06-06 20:28:12.703 E/AndroidRuntime(3193): 	at android.support.v7.widget.RecyclerView.onLayout(Unknown Source)
06-06 20:28:12.703 E/AndroidRuntime(3193): 	at android.view.View.layout(View.java:15686)
06-06 20:28:12.703 E/AndroidRuntime(3193): 	at android.view.ViewGroup.layout(ViewGroup.java:5107)
06-06 20:28:12.703 E/AndroidRuntime(3193): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
06-06 20:28:12.703 E/AndroidRuntime(3193): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
06-06 20:28:12.703 E/AndroidRuntime(3193): 	at android.view.View.layout(View.java:15686)
06-06 20:28:12.703 E/AndroidRuntime(3193): 	at android.view.ViewGroup.layout(ViewGroup.java:5107)
06-06 20:28:12.703 E/AndroidRuntime(3193): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
06-06 20:28:12.703 E/AndroidRuntime(3193): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
06-06 20:28:12.703 E/AndroidRuntime(3193): 	at android.view.View.layout(View.java:15686)
06-06 20:28:12.703 E/AndroidRuntime(3193): 	at android.view.ViewGroup.layout(ViewGroup.java:5107)
06-06 20:28:12.703 E/AndroidRuntime(3193): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
06-06 20:28:12.703 E/AndroidRuntime(3193): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
06-06 20:28:12.703 E/AndroidRuntime(3193): 	at android.view.View.layout(View.java:15686)
06-06 20:28:12.703 E/AndroidRuntime(3193): 	at android.view.ViewGroup.layout(ViewGroup.java:5107)
06-06 20:28:12.703 E/AndroidRuntime(3193): 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
06-06 20:28:12.703 E/AndroidRuntime(3193): 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
06-06 20:28:12.703 E/AndroidRuntime(3193): 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
06-06 20:28:12.703 E/AndroidRuntime(3193): 	at android.view.View.layout(View.java:15686)
06-06 20:28:12.703 E/AndroidRuntime(3193): 	at android.view.ViewGroup.layout(ViewGroup.java:5107)
06-06 20:28:12.703 E/AndroidRuntime(3193): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
06-06 20:28:12.703 E/AndroidRuntime(3193): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
06-06 20:28:12.703 E/AndroidRuntime(3193): 	at android.view.View.layout(View.java:15686)
06-06 20:28:12.703 E/AndroidRuntime(3193): 	at android.view.ViewGroup.layout(ViewGroup.java:5107)
06-06 20:28:12.703 E/AndroidRuntime(3193): 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
06-06 20:28:12.703 E/AndroidRuntime(3193): 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
06-06 20:28:12.703 E/AndroidRuntime(3193): 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
06-06 20:28:12.703 E/AndroidRuntime(3193): 	at android.view.View.layout(View.java:15686)
06-06 20:28:12.703 E/AndroidRuntime(3193): 	at android.view.ViewGroup.layout(ViewGroup.java:5107)
06-06 20:28:12.703 E/AndroidRuntime(3193): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
06-06 20:28:12.703 E/AndroidRuntime(3193): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
06-06 20:28:12.703 E/AndroidRuntime(3193): 	at android.view.View.layout(View.java:15686)
06-06 20:28:12.703 E/AndroidRuntime(3193): 	at android.view.ViewGroup.layout(ViewGroup.java:5107)
06-06 20:28:12.703 E/AndroidRuntime(3193): 	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2086)
06-06 20:28:12.703 E/AndroidRuntime(3193): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1843)
06-06 20:28:12.703 E/AndroidRuntime(3193): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1061)
06-06 20:28:12.703 E/AndroidRuntime(3193): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5895)
06-06 20:28:12.703 E/AndroidRuntime(3193): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
06-06 20:28:12.703 E/AndroidRuntime(3193): 	at android.view.Choreographer.doCallbacks(Choreographer.java:580)
06-06 20:28:12.703 E/AndroidRuntime(3193): 	at android.view.Choreographer.doFrame(Choreographer.java:550)
06-06 20:28:12.703 E/AndroidRuntime(3193): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
06-06 20:28:12.703 E/AndroidRuntime(3193): 	at android.os.Handler.handleCallback(Handler.java:739)
06-06 20:28:12.703 E/AndroidRuntime(3193): 	at android.os.Handler.dispatchMessage(Handler.java:95)
06-06 20:28:12.703 E/AndroidRuntime(3193): 	at android.os.Looper.loop(Looper.java:135)
06-06 20:28:12.703 E/AndroidRuntime(3193): 	at android.app.ActivityThread.main(ActivityThread.java:5345)
06-06 20:28:12.703 E/AndroidRuntime(3193): 	at java.lang.reflect.Method.invoke(Native Method)
06-06 20:28:12.703 E/AndroidRuntime(3193): 	at java.lang.reflect.Method.invoke(Method.java:37
```

**Comment by kollerlukas** [comment]
Deofustcated Stack Trace:
`06-06 20:28:12.703 E/AndroidRuntime(3193): FATAL EXCEPTION: main
06-06 20:28:12.703 E/AndroidRuntime(3193): Process: us.koller.cameraroll, PID: 3193
06-06 20:28:12.703 E/AndroidRuntime(3193): java.lang.IllegalArgumentException: Failed to find storage device at /storage/emulated/legacy/Download
06-06 20:28:12.703 E/AndroidRuntime(3193): at android.os.Environment.isExternalStorageRemovable(Environment.java:963)
06-06 20:28:12.703 E/AndroidRuntime(3193): at us.koller.cameraroll.a.d.a.a.a(Unknown Source)
06-06 20:28:12.703 E/AndroidRuntime(3193): at us.koller.cameraroll.a.d.a.e.a(Unknown Source)
06-06 20:28:12.703 E/AndroidRuntime(3193): at us.koller.cameraroll.a.d.a.a(Unknown Source)
06-06 20:28:12.703 E/AndroidRuntime(3193): at android.support.v7.widget.RecyclerView$a.a(Unknown Source)
06-06 20:28:12.703 E/AndroidRuntime(3193): at android.support.v7.widget.RecyclerView$a.b(Unknown Source)
06-06 20:28:12.703 E/AndroidRuntime(3193): at android.support.v7.widget.RecyclerView$o.a(Unknown Source)
06-06 20:28:12.703 E/AndroidRuntime(3193): at android.support.v7.widget.RecyclerView$o.a(Unknown Source)
06-06 20:28:12.703 E/AndroidRuntime(3193): at android.support.v7.widget.RecyclerView$o.a(Unknown Source)
06-06 20:28:12.703 E/AndroidRuntime(3193): at android.support.v7.widget.RecyclerView$o.c(Unknown Source)
06-06 20:28:12.703 E/AndroidRuntime(3193): at android.support.v7.widget.LinearLayoutManager$c.a(Unknown Source)
06-06 20:28:12.703 E/AndroidRuntime(3193): at android.support.v7.widget.GridLayoutManager.a(Unknown Source)
06-06 20:28:12.703 E/AndroidRuntime(3193): at android.support.v7.widget.LinearLayoutManager.a(Unknown Source)
06-06 20:28:12.703 E/AndroidRuntime(3193): at android.support.v7.widget.LinearLayoutManager.c(Unknown Source)
06-06 20:28:12.703 E/AndroidRuntime(3193): at android.support.v7.widget.GridLayoutManager.c(Unknown Source)
06-06 20:28:12.703 E/AndroidRuntime(3193): at android.support.v7.widget.RecyclerView.O(Unknown Source)
06-06 20:28:12.703 E/AndroidRuntime(3193): at android.support.v7.widget.RecyclerView.p(Unknown Source)
06-06 20:28:12.703 E/AndroidRuntime(3193): at android.support.v7.widget.RecyclerView.onLayout(Unknown Source)
06-06 20:28:12.703 E/AndroidRuntime(3193): at android.view.View.layout(View.java:15686)
06-06 20:28:12.703 E/AndroidRuntime(3193): at android.view.ViewGroup.layout(ViewGroup.java:5107)
06-06 20:28:12.703 E/AndroidRuntime(3193): at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
06-06 20:28:12.703 E/AndroidRuntime(3193): at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
06-06 20:28:12.703 E/AndroidRuntime(3193): at android.view.View.layout(View.java:15686)
06-06 20:28:12.703 E/AndroidRuntime(3193): at android.view.ViewGroup.layout(ViewGroup.java:5107)
06-06 20:28:12.703 E/AndroidRuntime(3193): at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
06-06 20:28:12.703 E/AndroidRuntime(3193): at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
06-06 20:28:12.703 E/AndroidRuntime(3193): at android.view.View.layout(View.java:15686)
06-06 20:28:12.703 E/AndroidRuntime(3193): at android.view.ViewGroup.layout(ViewGroup.java:5107)
06-06 20:28:12.703 E/AndroidRuntime(3193): at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
06-06 20:28:12.703 E/AndroidRuntime(3193): at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
06-06 20:28:12.703 E/AndroidRuntime(3193): at android.view.View.layout(View.java:15686)
06-06 20:28:12.703 E/AndroidRuntime(3193): at android.view.ViewGroup.layout(ViewGroup.java:5107)
06-06 20:28:12.703 E/AndroidRuntime(3193): at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
06-06 20:28:12.703 E/AndroidRuntime(3193): at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
06-06 20:28:12.703 E/AndroidRuntime(3193): at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
06-06 20:28:12.703 E/AndroidRuntime(3193): at android.view.View.layout(View.java:15686)
06-06 20:28:12.703 E/AndroidRuntime(3193): at android.view.ViewGroup.layout(ViewGroup.java:5107)
06-06 20:28:12.703 E/AndroidRuntime(3193): at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
06-06 20:28:12.703 E/AndroidRuntime(3193): at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
06-06 20:28:12.703 E/AndroidRuntime(3193): at android.view.View.layout(View.java:15686)
06-06 20:28:12.703 E/AndroidRuntime(3193): at android.view.ViewGroup.layout(ViewGroup.java:5107)
06-06 20:28:12.703 E/AndroidRuntime(3193): at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
06-06 20:28:12.703 E/AndroidRuntime(3193): at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
06-06 20:28:12.703 E/AndroidRuntime(3193): at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
06-06 20:28:12.703 E/AndroidRuntime(3193): at android.view.View.layout(View.java:15686)
06-06 20:28:12.703 E/AndroidRuntime(3193): at android.view.ViewGroup.layout(ViewGroup.java:5107)
06-06 20:28:12.703 E/AndroidRuntime(3193): at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
06-06 20:28:12.703 E/AndroidRuntime(3193): at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
06-06 20:28:12.703 E/AndroidRuntime(3193): at android.view.View.layout(View.java:15686)
06-06 20:28:12.703 E/AndroidRuntime(3193): at android.view.ViewGroup.layout(ViewGroup.java:5107)
06-06 20:28:12.703 E/AndroidRuntime(3193): at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2086)
06-06 20:28:12.703 E/AndroidRuntime(3193): at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1843)
06-06 20:28:12.703 E/AndroidRuntime(3193): at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1061)
06-06 20:28:12.703 E/AndroidRuntime(3193): at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5895)
06-06 20:28:12.703 E/AndroidRuntime(3193): at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
06-06 20:28:12.703 E/AndroidRuntime(3193): at android.view.Choreographer.doCallbacks(Choreographer.java:580)
06-06 20:28:12.703 E/AndroidRuntime(3193): at android.view.Choreographer.doFrame(Choreographer.java:550)
06-06 20:28:12.703 E/AndroidRuntime(3193): at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
06-06 20:28:12.703 E/AndroidRuntime(3193): at android.os.Handler.handleCallback(Handler.java:739)
06-06 20:28:12.703 E/AndroidRuntime(3193): at android.os.Handler.dispatchMessage(Handler.java:95)
06-06 20:28:12.703 E/AndroidRuntime(3193): at android.os.Looper.loop(Looper.java:135)
06-06 20:28:12.703 E/AndroidRuntime(3193): at android.app.ActivityThread.main(ActivityThread.java:5345)
06-06 20:28:12.703 E/AndroidRuntime(3193): at java.lang.reflect.Method.invoke(Native Method)
06-06 20:28:12.703 E/AndroidRuntime(3193): at java.lang.reflect.Method.invoke(Method.java:37
`

**Comment by kollerlukas** [comment]
What device and Android Version are you running?

**Comment by kollerlukas** [comment]
Should be fixed now.
https://github.com/kollerlukas/Camera-Roll-Android-App/commit/fc882d99ec549c416d66029ab26b8b104cf32f1c
