### ISSUE TITLE
Extended Folder Capabilities [Feature]

### ISSUE THREAD

**Issue by TGNYC** [kollerlukas/Camera-Roll-Android-App#4]
The app should have the ability to make and delete folders, as well as being able to select images from a folder and being able to move them folder to folder. When inside a folder, being able to sort images by different criteria would be a good feature.

Other gallery apps like [Simple Gallery](https://github.com/SimpleMobileTools/Simple-Gallery/) has these features, so take a look there if you need some ideas for code.

**Comment by kollerlukas** [comment]
It is possible to move, copy, delete and create folders/files from the file explorer. But I will add  a more convenient solution.

**Comment by TGNYC** [comment]
tbh a gallery app isn't supposed to be a file explorer. I think having one is a good, innovative idea, but the features should probably be baked into the actual gallery part of the app.

**Comment by kollerlukas** [comment]
https://github.com/kollerlukas/Camera-Roll-Android-App/commit/49a0b5787587623f316ed407be9f984da3bc0092
