### ISSUE TITLE
Make Video Icon on the thumbnails more visible

### ISSUE THREAD

**Issue by jerryn70** [kollerlukas/Camera-Roll-Android-App#41]
The video icon on the thumbnails is not visible on some videos because it of transparency. 

What about changing it to like this 
![screenshot_20170615-125244 01](https://user-images.githubusercontent.com/23030460/27170417-696c7c52-51cb-11e7-8a40-bdd007ee0085.png)

**Comment by kollerlukas** [comment]
I can make them more opaque.

**Comment by kollerlukas** [comment]
I added a shadow for the indicators.
https://github.com/kollerlukas/Camera-Roll-Android-App/commit/bd455df68c9c08a610f4f6387a721136ea9e6f47
