### ISSUE TITLE
Include / Exclude  Folders option

### ISSUE THREAD

**Issue by jerryn70** [kollerlukas/Camera-Roll-Android-App#42]
So that I can manually add/remove/view excluded folders.

**Comment by kollerlukas** [comment]
You can currently view excluded folder, when you enable hidden Folder.

**Comment by dkanada** [comment]
This would be nice, I have music saved locally on my phone and since I can't exclude the base path I would have to manually exclude every single album art on my phone.

**Comment by kollerlukas** [comment]
You can actually go into the file explorer and exclude the music folder.

**Comment by dkanada** [comment]
That worked great for my issue, thanks for the tip!

**Comment by kollerlukas** [comment]
https://github.com/kollerlukas/Camera-Roll-Android-App/commit/b3ae9e4b12b7a9ba8c58480d30215a88908dec2f
