### ISSUE TITLE
Image/Video informations showing as unknown

### ISSUE THREAD

**Issue by jerryn70** [kollerlukas/Camera-Roll-Android-App#43]
I'm attaching two screenshots , one is from quickpic gallery and other is from camera roll .
Quickpic shows the date and other info's about the image but camera roll is not showing any details.
![screenshot_20170615-162808 01](https://user-images.githubusercontent.com/23030460/27178668-d3b6389c-51e8-11e7-9400-61ac46ca2688.png)
![screenshot_20170615-162853 01](https://user-images.githubusercontent.com/23030460/27178681-e4038a42-51e8-11e7-984c-3e34aa300d34.png)

**Comment by jerryn70** [comment]
In the above post image date is shown as unknown.

**Comment by kollerlukas** [comment]
Thats because there is no date im the Exif Data or there is no Exif Data for this photo. In these cases I could use the date I get from MediaStore (Thats probably what QuickPic is doing).

**Comment by kollerlukas** [comment]
https://github.com/kollerlukas/Camera-Roll-Android-App/commit/b79ee6d6ca966e5a46e7290105286b132dae7ada
