### ISSUE TITLE
RAW Support

### ISSUE THREAD

**Issue by HeyItsJono** [kollerlukas/Camera-Roll-Android-App#46]
Hey there, I was wondering if you'd consider adding support for viewing RAW images taken with apps like Manual Camera. Thanks!!  

_Sent from my Huawei Nexus 6P using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by kollerlukas** [comment]
Just added experimental RAW support
https://github.com/kollerlukas/Camera-Roll-Android-App/commit/30ca7cf825dd01d6221f8f3fe6310691b3fb05ef

**Comment by fredgolightly** [comment]
Thanks for dng support, however, on Pixel 2 you can't zoom in at all, any chance this could be fixed?
