### ISSUE TITLE
Please add Password/Pin/Fingerprint protection to hidden folders

### ISSUE THREAD

**Issue by jahirfiquitiva** [kollerlukas/Camera-Roll-Android-App#49]

**Comment by kollerlukas** [comment]
Currently hidden folders are folders, where either the filename starts with a period or the folder has a nomedia file inside it. If I would add a Password for those folders other applications could still read those folders without a password.
Also I am not planning on adding any security features.

**Comment by jahirfiquitiva** [comment]
I know other apps would still read the files, but QuickPic has this. I think is a good feature, but ok.
