### ISSUE TITLE
Exclude Folders [Bug]

### ISSUE THREAD

**Issue by TGNYC** [kollerlukas/Camera-Roll-Android-App#5]
Device: OnePlus 3
Android Version: 7.1.1
App Version: 1.3 Beta (15)
-----
If you exclude a folder, there is no way of including it in the app unless you wipe the app's memory (not cache) completely. There should probably be a way of including folders, or maybe excluded folders should be able to be viewed if the Hidden Folders option is enabled.

**Comment by kollerlukas** [comment]
You can go into the file explorer and unexcluded there.
But I see your point, it should be easier to un-exclude a folder.

**Comment by kollerlukas** [comment]
See latest commit: excluded albums are now shown together with hidden albums.
