### ISSUE TITLE
Possibility to set the wallpaper

### ISSUE THREAD

**Issue by KabbAmine** [kollerlukas/Camera-Roll-Android-App#53]
Congratulations for your app, its a nice piece of software and I'm sure that it will be better in the future.

I'm not aware of the planned features, but the only thing that make me not use camera roll is the inability to set an image as a wallpaper without a third party app.

Are you planning to add this feature or did I miss it?

**Comment by kollerlukas** [comment]
Done!
https://github.com/kollerlukas/Camera-Roll-Android-App/commit/63cce9eb41ed1e0f5b60dd86d138e15d7c9edafc
