### ISSUE TITLE
Badges For README?

### ISSUE THREAD

**Issue by Sylvia-Keren-Happuch** [kollerlukas/Camera-Roll-Android-App#56]
Hi @kollerlukas,
thanks for your awesome Android app! 😍
What do you think of adding [Travis CI](https://travis-ci.org/), [Semaphore](https://semaphoreci.com/), [Code Climate](https://codeclimate.com/), [codebeat](https://codebeat.co/) or [Codacy](https://www.codacy.com/)?
Example: [https://github.com/nextcloud/android](https://github.com/nextcloud/android)

**Comment by kollerlukas** [comment]
working on it...

**Comment by kollerlukas** [comment]
now added Codacy and Travis
