### ISSUE TITLE
Toolbar text and icons are not tinted on new version

### ISSUE THREAD

**Issue by jahirfiquitiva** [kollerlukas/Camera-Roll-Android-App#58]
They are grey/black and they are pretty much invisible in many cases.

![screenshot_20170724-130245](https://user-images.githubusercontent.com/10360816/28538222-17807daa-7073-11e7-9ff6-ddde6a333ae8.png)

![screenshot_20170724-130251](https://user-images.githubusercontent.com/10360816/28538220-16c3dbd2-7073-11e7-823d-a15746e55c8a.png)

**Comment by kollerlukas** [comment]
Is this only with the light the or also with the dark?

**Comment by kollerlukas** [comment]
Found the issue: textColorPrimary/-Secondary weren't set for the light theme
