### ISSUE TITLE
Auto-refresh on app open

### ISSUE THREAD

**Issue by TGNYC** [kollerlukas/Camera-Roll-Android-App#6]
It is quite annoying to have to either hit the refresh button everytime you take a new picture, or restart the app (which I never do). Could you please make it so that the app refreshes every time it is opened, even if I open it from the recent apps menu?

**Comment by jahirfiquitiva** [comment]
I second this. Could you please update the pictures in `onResume()` or something @kollerlukas ?

**Comment by kollerlukas** [comment]
I will look into a way of automatically refreshing the app.

**Comment by jahirfiquitiva** [comment]
@kollerlukas  Great. Thank you.

**Comment by pink-bird** [comment]
When opening app on Android 7.0, loading time takes very long, then getting feedback "Loading failed" (see pic). 

![screenshot_20170709-115048](https://user-images.githubusercontent.com/19912504/27993089-92d83db2-64a2-11e7-86f5-cd804e978274.png)

**Comment by kollerlukas** [comment]
@pink-bird please open a new issue for this. This is a bug.

**Comment by kollerlukas** [comment]
https://github.com/kollerlukas/Camera-Roll-Android-App/commit/c8cbb3dced65d7af7dd8abb16cb0a7b6d74dd27d
