### ISSUE TITLE
A few things

### ISSUE THREAD

**Issue by gamehelp16** [kollerlukas/Camera-Roll-Android-App#62]
I hope it's okay to dump all these into a single issue instead of giving them each own issues hehe

Bugs:

1. When the "MediaRetriever" setting is on, some pictures cause the app to crash when opened (looks like the pictures that cause the error are the ones which don't appear when the option is turned off).

Suggestions (most of them are minor things):

1. On the image info box, I think it's better if unknown exif data aren't shown at all (for example when the exposure is unknown, no need to show "exposure: unknown").
2. After changing some settings (like MediaRetriever) it would be nice if the main view is automatically refreshed instead of refreshing manually.
3. Swipe down to refresh would also be a nice addition.
4. Add option to sort descending or ascending.
5. When you scroll to the very bottom of the main view and do a quick swipe upwards, the view won't scroll all the way to the top (kinda hard to explain but I hope you got it).
6. White theme with the light green accent theme doesn't seem to go really well ;)
7. On the white theme, it would be nicer if the action bar (on the main view) and folder name has black color instead of grey.
8. There should be a maximum value for the column count option.
9. The preview image on the style settings are a little bit blurry (yes I know this is really minor but it kinda bothers me a bit hehe).
10. A "letter bubble" on the scrollbar on the main view would be nice too.

Also thank you for making the app, I think this app has the best design over all other gallery apps! I hope it can mature soon.

**Comment by kollerlukas** [comment]
5: only happens with the nestedReycleView-Style; I don't know what causes this
7: done.
8: Why?
9: done, changed them vectorDrawables
10: What Letter do you want to show when sorting by date is set?

**Comment by gamehelp16** [comment]
8. I think it's just funny that you can set the column count to something like 100 making the thumbnails really small and that doesn't seem to be useful.
10. Ah yes I didn't think about that :sweat_smile:

**Comment by kollerlukas** [comment]
1: Should be the save thing that caused the crash with hidden images. This is fixed now
https://github.com/kollerlukas/Camera-Roll-Android-App/commit/37eaf5f0de740f4573f56d2c4856dd1556064263

**Comment by kollerlukas** [comment]
I going to close this issue, because most of your suggestions are worked off.

**Comment by gamehelp16** [comment]
Alright, thanks for developing this awesome app!
