### ISSUE TITLE
SD card access 

### ISSUE THREAD

**Issue by vipuln** [kollerlukas/Camera-Roll-Android-App#64]
App crashes right after I try to give permission to SD card access..

**Comment by kollerlukas** [comment]
What kind of File operation were you trying to do?

**Comment by vipuln** [comment]
Delete, move all operations : from or to SD card.. will prompt me need SD card access permissions (dailog box) as soon as I click ok app crashes.. I tryed reinstalling.. clear cache.. not get solution.. plz help

**Comment by kollerlukas** [comment]
What device are you on?

**Comment by vipuln** [comment]
Moto G2 rooted linage 14.1 os

**Comment by kollerlukas** [comment]
Was this issue fixed with the last upate?

**Comment by vipuln** [comment]
No friend.. I installed update.. but still app crashes..
I have attached screen shot plz check..

On Aug 11, 2017 9:47 PM, "Lukas Koller" <notifications@github.com> wrote:

Was this issue fixed with the last upate?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/kollerlukas/Camera-Roll-Android-App/issues/64#issuecomment-321856036>,
or mute the thread

**Comment by kollerlukas** [comment]
Would it be possible that you send me a stack trace?

**Comment by dkanada** [comment]
@vipuln do you have the LineageOS file manager disabled on your phone? That could be the issue, LineageOS only handles SD card access in the included file manager.

**Comment by vipuln** [comment]
Yes that worked like charm... Thank you so much for finding solution...

**Comment by kollerlukas** [comment]
@vipuln So it is working now?

**Comment by vipuln** [comment]
Yes working fine..

I got one more bug.. when I try to set wallpaper it says toast as error..

**Comment by kollerlukas** [comment]
@vinpuln Pleaes open a new issue for that.
I am going to close this issue since it is fixed now.
