### ISSUE TITLE
Not visible after copying on the SD Card

### ISSUE THREAD

**Issue by taaem** [kollerlukas/Camera-Roll-Android-App#65]
When I copy a picture into a folder on my SD Card it shows that it is successfully copied, but I can't see it in the new folder. The Copy action was successful I can see the picture in a different gallery app just fine but in Camera Roll itself it doesn't even show after reloading the pictures. 
This only happens if I copy the pictures to the sd card, on the internal storage everything is fine.
This is on Android 7.1.2. 
I was thinking maybe your copying the image correctly, but then there is an issue with adding the picture to the Media Scanner of Android.

**Comment by kollerlukas** [comment]
Thats weird. 
After any file operation MediaScannerConnection.scanFile() is called with all the affected files.
I will look into this issue.

**Comment by taaem** [comment]
Are you adding the file via the absolute path like /storage/...? I remember the media scanner using different file paths for external storage so they can control who has access but I don't know if that's also the case for adding files

**Comment by taaem** [comment]
Strange I just tried copying files again and it showed them directly...

**Comment by kollerlukas** [comment]
So its working?

**Comment by taaem** [comment]
Just tried with a new folder and it seems to be working fine now 
I think you can close this
