### ISSUE TITLE
zoom

### ISSUE THREAD

**Issue by sinarahimpoor** [kollerlukas/Camera-Roll-Android-App#66]
some time zoom not working !!!🤔

**Comment by inDream** [comment]
I think zoom is disabled in "loading" state? I can zoom after clicked Info and wait until info loaded.

**Comment by kollerlukas** [comment]
What kind of images are you trying to view?

**Comment by kollerlukas** [comment]
I am going to close this issue since there is no response and I can not reproduce this issue.

**Comment by inDream** [comment]
It normal jpg image.

**Comment by kollerlukas** [comment]
What Android Version and Device are you on?

**Comment by inDream** [comment]
Sony Z5 Android 6.0.1 (32.2.A.0.305)

**Comment by kollerlukas** [comment]
Does this always happen with the same images or randomly?

**Comment by inDream** [comment]
It only happens with photos taken by camera (may be related to exif?)

**Comment by dkanada** [comment]
I also noticed this but it only happened once and I wasn't able to reproduce the error. No zoom control until I restarted the app and then my phone, not sure which fixed it.

**Comment by kollerlukas** [comment]
Is this still an issue?

**Comment by inDream** [comment]
It's fixed for me, thank you very much.
