### ISSUE TITLE
Add a style for albums view that is exactly the same as the inner albums view

### ISSUE THREAD

**Issue by jahirfiquitiva** [kollerlukas/Camera-Roll-Android-App#7]
What I mean is that **this**:
![screenshot_20170506-222538](https://cloud.githubusercontent.com/assets/10360816/25777742/284f69e8-32ac-11e7-9e4b-4d4a8df83eeb.png)

Has a style option so it can look like **this**:
![screenshot_20170506-222550](https://cloud.githubusercontent.com/assets/10360816/25777746/40f971aa-32ac-11e7-9324-a2cf76266215.png)

**Thanks in advance**

**Comment by kollerlukas** [comment]
Yeah sure!

**Comment by jahirfiquitiva** [comment]
@kollerlukas 

Thank you so much. I love your gallery app.

**Comment by kollerlukas** [comment]
done.

**Comment by jahirfiquitiva** [comment]
@kollerlukas Thank you
