### ISSUE TITLE
The move dialog is extremely unresponsive on my phone.

### ISSUE THREAD

**Issue by dkanada** [kollerlukas/Camera-Roll-Android-App#70]
When I try to move one or more images the move adapter does not scroll without multiple tries and selecting a new folder only shows a check half the time. The cover images for each folder also load slowly, I am usually finished selecting a new folder before the images are completely loaded.

**Comment by kollerlukas** [comment]
Weird. What device and Android version are you on?

**Comment by dkanada** [comment]
LineageOS 14.1 on a Motorola X Pure.

**Comment by kollerlukas** [comment]
That really weird. I just flashed lineage os on my Moto x 2014 and I don't have any issues.

**Comment by dkanada** [comment]
I just built the app again and it seems to be working now, must have been fixed since then. I will close the issue for now and reopen if I have issues again.
