### ISSUE TITLE
Deleted photos not being scanned on OnePlus Devices

### ISSUE THREAD

**Issue by Yixuan-Wang** [kollerlukas/Camera-Roll-Android-App#71]
My phone is OnePlus 5(ONEPLUS A5000 cheeseburger, Android 7.1.1) and when I delete a photo in Camera Roll(1.6.1 Beta), it would leave a black box there. But after rebooting the phone, the problem is solved. When MediaRetriever is enabled, everything is fine. Seems there's problem with OnePlus's Hydrogen OS, the stock gallery reports 'image corrupted'.
![1](https://user-images.githubusercontent.com/21151119/29483175-5a13e7fa-84d3-11e7-932c-f7c62928fd1c.png)
![2](https://user-images.githubusercontent.com/21151119/29483176-5cd4a97a-84d3-11e7-8093-85ebb9ce549d.jpg)

**Comment by Yixuan-Wang** [comment]
But when MediaRetriever is enabled, everything is fine.

**Comment by kollerlukas** [comment]
Does this only happen with deleted files?
Are new copied files scanned correctly?

_Sent from my Google Pixel using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Yixuan-Wang** [comment]
Only deleted files. New copied files are scanned correctly.

**Comment by kollerlukas** [comment]
I also had other users send me feeback and reporting the same issue.

**Comment by kollerlukas** [comment]
With the last update I added a scan-button to the file explorer to trigger the MediaScanner. Can you please try and delete a file, and after that trigger the MediaScanner through the file explorer?

**Comment by Yixuan-Wang** [comment]
I'm very sorry that I might not be able to do that, as I flashed another ROM. On the custom ROM(Resurrection Remix) even 1.6.1 beta worked perfectly.

**Comment by Sibah** [comment]
I triggered the MediaScanner in the file explorer but it did not solve the problem. I also found out that pictures deleted with CameraRoll are not properly deleted on Oneplus devices. I can still see them with Solid Explorer and the size of pictures is 0 B. Even Solid Explorer is unable to delete it.

**Comment by kollerlukas** [comment]
If even SolidExplorer is unable to delete them I would assume that this is a OnePlus issue.

**Comment by Sibah** [comment]
Might be. It's weird that this is the only gallery app with this issue, as other apps delete files just fine.

**Comment by AnonymerNiklasistanonym** [comment]
> [...] are not properly deleted on Oneplus devices. [...]

> [...] this is a OnePlus issue.

I have nothing groundbreaking to report, just that not all OnePlus devices are experiencing this problem.

 I just tried to delete a photo on my OnePlus X (Android 6.0.1 with no ROMs or custom things) and everything worked fine (No 0B file in Solid Explorer for me). The only thing I noticed is that the deletion process takes some seconds but in the end the file is 100% gone.

**Comment by Sibah** [comment]
[Log_2017-9-12_23-55-27.txt](https://github.com/kollerlukas/Camera-Roll-Android-App/files/1297496/Log_2017-9-12_23-55-27.txt)
I'm attaching a log recorded when trying to delete a picture in CameraRoll. Lots of FileNotFoundException. Hope it helps.

**Comment by kollerlukas** [comment]
The FileNotFoundException are send by Glide (the image loading library I am using), because it can't load the deleted pictures.

**Comment by krux3r** [comment]
I'm having the same problem, but sometimes the app deletes the photo, sometimes it dissapears and then reappears after a while, and sometimes it deletes it from Camera Roll but the photo is visible in the stock gallery.
I have Huawei P10 Lite, stock 7.0

**Comment by kollerlukas** [comment]
I just pushed an update (v1.0.1) to the PlayStore. Can you please let me know if this issue is still present in the new update.
Thanks in advance!

**Comment by Sibah** [comment]
Photos are now correctly deleted. However, a manual refresh is required to make them disappear from gallery.

**Comment by krux3r** [comment]
I haven't gotten the update lol, hope it will come asap.

**Comment by kollerlukas** [comment]
@Sibah Would it be possible that you send me another log? That would be great. Thanks in advance!

**Comment by Sibah** [comment]
[Log_2017-10-01_20-21-23.txt](https://github.com/kollerlukas/Camera-Roll-Android-App/files/1347356/Log_2017-10-01_20-21-23.txt)
Here you go. No errors in the log this time, just some debug info.

**Comment by kollerlukas** [comment]
@Sibah Thank you!

**Comment by kollerlukas** [comment]
Does the new update (v1.0.2) change anything?

**Comment by Sibah** [comment]
No noticeable change. Photos get deleted fine but still have to do manual refresh to make them disappear.

**Comment by krux3r** [comment]
@kollerlukas for me the app now deletes the photos as it should, and there is no need to refresh. Only thing is the deleting is super slow, like more than 5 seconds. Yeah and this is for deleting photos from SD. Internal memory deleting is working as it should.

**Comment by kollerlukas** [comment]
@krux3r So is the issue fixed now!?

**Comment by krux3r** [comment]
@kollerlukas So, deleting photos on SD works, but is not instant, it takes a while, check here: https://youtu.be/xSzfqKRV_uc

**Comment by Baldesarra** [comment]
o I tested a few things.

When I have Media retriever disabled, I cannot correctly delete a picture. I can wait for minutes and nothing happens. But when I go back to the album, the picture is half deleted (a "missing picture thumbnail" remains).

After I check "reload", the picture is finally gone.

Nevertheless there is still a "missing picture thumbnail" on other galleries. So the picture isn't 100% deleted from the phone.

Same happens when media retriever is enabled. I don't have to click on "reload" but other galleries still show the black thumbnail of a missing picture.

**Comment by krux3r** [comment]
@Baldesarra I had the same exact issue before. But now it is working as it should, only deleting is slow, nothing else.

**Comment by kollerlukas** [comment]
Would it be possible that someone of you installs this apk, and let's me know if the issue still perists?
Thanks in advance!

https://drive.google.com/file/d/0ByIpTtgzZGCbMTJfVVlVTHh4UVE/view?usp=sharing

**Comment by Baldesarra** [comment]
Working here!
Using oneplus 5 with latest OxygenOS.

Everything great now even with media retriever turned off. Thanks!

**Comment by Sibah** [comment]
Fixed for me too. 👍

**Comment by kollerlukas** [comment]
Thanks guys!
Just pushed the update to the play store.

**Comment by krux3r** [comment]
For me it leaves that broken photo after deleting, unfortunely.

**Comment by Baldesarra** [comment]
@krux3r
Have you tried to delete Data and Cache of the app before uninstalling it?

I've deleted Data, Cache. Then uninstalled the old version and re-installed the new one. Then it worked for me.

**Comment by krux3r** [comment]
Just tried, didn't work. It stays the same lol
