### ISSUE TITLE
Reduce albums view cards margins

### ISSUE THREAD

**Issue by jahirfiquitiva** [kollerlukas/Camera-Roll-Android-App#8]
Currently, cards margin is (if I'm not wrong) 16dp and that's looks a bit too big, so please reduce it to just 8dp.

And also, please add an option to make those cards squared. I know I just requested a squared grid for albums view, but that's a flat view, and this one has cards, and some people might like it.

Thanks again.

**Comment by kollerlukas** [comment]
Already done that. I also made the marings equal.
![screenshot_20170506-205652](https://cloud.githubusercontent.com/assets/16599370/25777822/cad6ed0c-329e-11e7-9c9a-48de29b0d4a7.png)

**Comment by jahirfiquitiva** [comment]
They look better, but (from screenshot) I think margins are 8dp still :/

**Comment by jahirfiquitiva** [comment]
They look better, but (from screenshot) I think margins are 16dp still :/

**Comment by kollerlukas** [comment]
I actually like the 16dp margins better than the 8dp.
![screenshot_20170507-004644](https://cloud.githubusercontent.com/assets/16599370/25778845/d4e9d3de-32be-11e7-9957-f1ec9fa899c4.png)

**Comment by jahirfiquitiva** [comment]
@kollerlukas Can you please keep it with 8dp? Or maybe as an option in settings?
I think the smaller margin results in best utilized space.

**Comment by TGNYC** [comment]
I think 8dp looks better as well, so an option might be a good idea.
