### ISSUE TITLE
Selecting mode

### ISSUE THREAD

**Issue by lologolo** [kollerlukas/Camera-Roll-Android-App#84]
Can you change  the select a picture layout in nested Recyclerview because the albums are too big and they aren't centered.
However I think that the selecting mode in other styles is beautiful.

**Comment by kollerlukas** [comment]
You want to change the way how selected images are displayed in the nestedRecyclerViewStyle?

**Comment by lologolo** [comment]
I mean this activity 
![screenshot_20170903-123707](https://user-images.githubusercontent.com/31082204/30002261-55d9d69e-90a5-11e7-97b9-c76f269fe900.png)

**Comment by kollerlukas** [comment]
Thats a bug. It should look like this:
![screenshot_20170903-124554](https://user-images.githubusercontent.com/16599370/30002293-0a9268da-90a6-11e7-8c19-ff3802e22a9a.png)

**Comment by lologolo** [comment]
I think you have setted card layout as default style, despite me that I have nested Recyclerview.
The photo picker layout change depending to the default style, so I think that this is not a bug.
![picsart_09-03-01 34 41](https://user-images.githubusercontent.com/31082204/30002653-fd115cc6-90ae-11e7-9c8e-9456b1b8a82c.jpg)

**Comment by kollerlukas** [comment]
Yeah the default is the cards style.

**Comment by lologolo** [comment]
Can you center the albums?
![screenshot_20170903-145008](https://user-images.githubusercontent.com/31082204/30003004-9cef3008-90b7-11e7-990a-5ab53413aeb1.png)
