### ISSUE TITLE
Name "Gallery" in toolbar

### ISSUE THREAD

**Issue by marciozomb13** [kollerlukas/Camera-Roll-Android-App#88]
To a better feel of a system app in upper toolbar the name "Gallery" (localized) should be showed rather than Camera Roll. Note the app name in app drawer remains untouched.

**Comment by IzzySoft** [comment]
So if you use multiple gallery apps (e.g. for specific features), how to identify them in e.g. "recent apps" view without doubt if they all would show with "Gallery" in their toolbar? I'd find that confusing.

**Comment by marciozomb13** [comment]
App icon would be enough to identify it.

**Comment by kollerlukas** [comment]
Btw it is possible to set a different string as the Toolbar title & and as the TaskDescription label.
But I am still not too convinced by the idea of changing the Toolbar title.

**Comment by IzzySoft** [comment]
@marciozomb13 I'd prefer the title being clear, as I might confuse the icon (there might be another one looking too similar) – so I'm with Lukas here (not being convinced). And creating an option just for that is probably not favorable/justifiable for such a minor cosmetic thing.

Btw: I just "walked" my "recent apps". All of them show the app name in the title. So I don't see why we should make an exception to it.

**Comment by marciozomb13** [comment]
For English speaking users, Camera Roll sounds good, but for other language users this may sound odd, and not having a intuitive, localized name give the feel of an unfinished translation. But is up to you to decide. But please, could you export the strings for the app name in toolbar and recents, so we could choose a different name if we decide to compile from source. Thank you.

**Comment by IzzySoft** [comment]
I'm a native German speaker, @marciozomb13 – and member of the generation that grew up with "analogue cameras". Maybe that's the reason the name has a clear association for me: the "roll" inside the camera (German: "Rollfilm") is where the photos are on. For Italian natives "rullino" probably gives a similar association, for Spanish "rollo". Admitted: French, Portuguese, Russian and a couple of others might not have it – but I haven't checked whether Lukas might have localized the label for any language either.

Apart from that: your suggestion towards a `strings.xml` is a more than fair compromise. That way one could even provide translations for "special cases" like this (or for Klingon, if someone insists :wink:)

**Comment by marciozomb13** [comment]
Thank you. 👍

**Comment by kollerlukas** [comment]
Yesterday I added two strings to the `[strings_not_translateable.xml](https://github.com/kollerlukas/Camera-Roll-Android-App/blob/master/app/src/main/res/values/strings_not_translatable.xml)`

`<string name="task_description_label">@string/app_name</string>
    <string name="toolbar_title">@string/app_name</string>`

to easily change the TaskDeskriptionLabel & Toolbar title in the MainActivity.

@marciozomb13 Does this solve the issue for you?

**Comment by marciozomb13** [comment]
Yes! Thank you so much!
