### ISSUE TITLE
Add an option to show a FAB in albums view to open camera

### ISSUE THREAD

**Issue by jahirfiquitiva** [kollerlukas/Camera-Roll-Android-App#9]
I find the app's design really simple and minimalist. I love it.

But I also think it would be good to have a FAB to open camera directly from gallery. Maybe as an option in settings.

Thanks in advance.

**Comment by kollerlukas** [comment]
![screenshot_20170511-221039](https://cloud.githubusercontent.com/assets/16599370/25983109/0a44f758-3697-11e7-9ac4-790f40e77ec7.png)
Done.
