### ISSUE TITLE
Folder options

### ISSUE THREAD

**Issue by IzzySoft** [kollerlukas/Camera-Roll-Android-App#90]
Would it be possible to explicitly exclude/hide certain directories (e.g. "Screenshots"), and also have the possibility to show images from all folders (instead of just from one specific at a time)? At least the latter would go pretty well with other currently requested features such as browse by tags or sort by location – especially when using multiple camera apps which use different storage areas each (think of e.g. putting large high-res photos on the external card while keeping others internal for e.g. speed issues with series).

**Comment by kollerlukas** [comment]
You can already exlcude whole directories through the File Explorer.
So do you want one big album with all images in it?

**Comment by IzzySoft** [comment]
I must have missed the File Explorer – found it now. Figured that can also be done from the context menu directly with the specific "album" open from the viewer, so count that one solved.

For the second one: Yes, that was the idea: all directories which are not hidden – or, even better, "selected directories". Think of it like "master views" or "virtual directories". If a user could define them, that would e.g. offer the possibility to join all "camera folders" to one such "master view" (aka "all photos"), have another one for e.g. "all covers" (from the music), Screenshots, etc – and then (optionally) even hide the original folders. If one wished to, it were even possible to create specific "albums" like "Vacation 2017", "Family" etc – but that part could also be left to tags (#83).

**Comment by kollerlukas** [comment]
I just added the option to create Virtual Albums via settings & add paths the the virtual Album via the FileExplorer. This then creates an album with all the images from the included paths. So e.g for a "Camera" virtual album you just need to add the DCIM-folder.

**Comment by kollerlukas** [comment]
Is this issue then solved?

**Comment by IzzySoft** [comment]
Sorry for my late response, I just returned from vacation. That sounds great! Will have a look ASAP.

PS: Just wondering about the `versionName`: `versionCode` 29 is v1.7.2, and 30 is v1.0 – quite unusual. One would expect a "higher name". Will confuse the one or the other user :wink:
