### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by IzzySoft** [kollerlukas/Camera-Roll-Android-App#91]
Could you please leave a note what for CR wants to access Internet all the time – e.g. on opening a directory or a single photo? I'm not assuming anything evil here, but it confuses me at least a bit and I want to understand the reason. I could think of one but I'm not sure, so I'd rather know than speculate :wink:

**Comment by kollerlukas** [comment]
Actually the only reason Camera Roll has the INTERNET permission is to load the header image in the About section (to keep apk size smaller).
And Camera Roll uses the ACCESS_NETWORK_STATE to check if the phone is connected to Wifi, and then e.g. decide to use Geocoder to load the loaction name in the Info Dialog.

**Comment by IzzySoft** [comment]
Thanks, Lukas! The latter one was what I've speculated about in fact (Nominatim), as I noticed an "Internet request" was made for each photo I opened. I've just checked the details (XPrivacy) and see it indeed not only accesses network *info* (via ACCESS_NETWORK_STATE: `isConnected()` is quite clear from what you just wrote, but `getLinkAdresses()` still confuses me), which is explained by your second paragraph but also something via INTERNET, which is probably what your first paragraph is about. Not being an Android dev, I'm not sure about the details: does using a WebView (which is what I guess you're talking about) trigger that, even if no "external link"/"Internet *access"* is involved?

To give some background of my question: Purely "informal", definitely not "accusing of evil-doing" (you don't upload the pics or stats about them anywhere, I trust). It's just that, as a "privacy advocate" I want to understand what's going on there and be sure what I recommend my fellow users *while being able to give reasons* why I can do so despite of "suspicious indicators" :wink:

**Comment by kollerlukas** [comment]
I actually don't really know what causes the `getLinkAddresses()` call, but I would guess that the method is called when checking the Network state.

**Comment by IzzySoft** [comment]
From a "privacy point of view": Wouldn't it be preferable to include that one image and drop the `INTERNET` permission instead? After all, the image will be downloaded anyway – and probably isn't that big.

**Comment by kollerlukas** [comment]
https://github.com/kollerlukas/Camera-Roll-Android-App/commit/6c0c13a2aa9b8270719e7e4311acc62d200f3cee

**Comment by IzzySoft** [comment]
Cool! Thanks! That should remove the last doubts :grin:

**Comment by IzzySoft** [comment]
And it seems the `.apk` didn't get any bigger by that. Or did you forget to include the "header image"? I didn't check yet, just noticed the update in the `releases/` section.

**Comment by kollerlukas** [comment]
I didn't include the image. I think the About section is fine without the image.
